'use client'
import { FormEvent,useState } from 'react'
import { Loader2,Plus,Save,Trash2 } from 'lucide-react'
type Project={id:string;name:string};type Dataset={id:string;project_id:string;name:string};type Mapping={id:string;dataset_id:string;column_name:string|null;confidence:number|null;approved:boolean};type Term={id:string;project_id:string;term:string;definition:string;domain:string|null;synonyms:string[];status:string;glossary_mappings:Mapping[]}
export function GlossaryManager({projects,datasets,initialTerms}:{projects:Project[];datasets:Dataset[];initialTerms:Term[]}){const[terms,setTerms]=useState(initialTerms);const[projectId,setProjectId]=useState(projects[0]?.id??'');const[term,setTerm]=useState('');const[definition,setDefinition]=useState('');const[domain,setDomain]=useState('');const[synonyms,setSynonyms]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
async function refresh(){const r=await fetch('/api/glossary');const p=await r.json();if(r.ok)setTerms(p.terms??[])}
async function create(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/glossary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,term,definition,domain,synonyms:synonyms.split(',').map(v=>v.trim()).filter(Boolean),status:'DRAFT'})});const p=await r.json();if(!r.ok)throw new Error(p.error??'Unable to create term.');setTerm('');setDefinition('');setMessage('Glossary term created.');await refresh()}catch(err){setMessage(err instanceof Error?err.message:'Unable to create term.')}finally{setBusy(false)}}
async function patch(id:string,body:Record<string,unknown>){const r=await fetch(`/api/glossary/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw new Error(p.error??'Update failed.');await refresh()}
async function remove(id:string){const r=await fetch(`/api/glossary/${id}`,{method:'DELETE'});if(r.ok)await refresh()}
async function map(termId:string,datasetId:string,columnName:string){const r=await fetch('/api/glossary/mappings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({termId,datasetId,columnName:columnName||null,confidence:1,approved:true})});const p=await r.json();if(!r.ok)throw new Error(p.error??'Mapping failed.');await refresh()}
return <div className="mt-6 grid gap-6 lg:grid-cols-[0.75fr_1.25fr]"><form onSubmit={create} className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">New business term</h2><div className="mt-5 grid gap-3"><select value={projectId} onChange={e=>setProjectId(e.target.value)} className="rounded-xl border px-3 py-2.5">{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Business term" className="rounded-xl border px-3 py-2.5"/><textarea value={definition} onChange={e=>setDefinition(e.target.value)} placeholder="Definition" rows={4} className="rounded-xl border px-3 py-2.5"/><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="Domain" className="rounded-xl border px-3 py-2.5"/><input value={synonyms} onChange={e=>setSynonyms(e.target.value)} placeholder="Synonyms, comma separated" className="rounded-xl border px-3 py-2.5"/><button disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 font-bold text-white">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}Create term</button>{message?<p className="text-sm text-slate-600">{message}</p>:null}</div></form><section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Terms and mappings</h2><div className="mt-5 space-y-3">{terms.map(t=><article key={t.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{t.term}</h3><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold">{t.status}</span></div><p className="mt-1 text-sm text-slate-600">{t.definition}</p><p className="mt-2 text-xs text-slate-400">{t.domain??'No domain'} · synonyms {(t.synonyms??[]).join(', ')||'none'}</p></div><div className="flex gap-2"><button onClick={()=>void patch(t.id,{status:t.status==='APPROVED'?'DRAFT':'APPROVED'})} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold"><Save className="mr-1 inline h-3.5 w-3.5"/> {t.status==='APPROVED'?'Unapprove':'Approve'}</button><button onClick={()=>void remove(t.id)} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></div></div><MappingForm term={t} datasets={datasets.filter(d=>d.project_id===t.project_id)} onMap={map}/><div className="mt-3 flex flex-wrap gap-2">{(t.glossary_mappings??[]).map(m=><span key={m.id} className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{datasets.find(d=>d.id===m.dataset_id)?.name??m.dataset_id}{m.column_name?`.${m.column_name}`:''}</span>)}</div></article>)}</div></section></div>}
function MappingForm({term,datasets,onMap}:{term:Term;datasets:Dataset[];onMap:(termId:string,datasetId:string,columnName:string)=>Promise<void>}){const[datasetId,setDatasetId]=useState(datasets[0]?.id??'');const[column,setColumn]=useState('');return <div className="mt-3 flex flex-wrap gap-2"><select value={datasetId} onChange={e=>setDatasetId(e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs">{datasets.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><input value={column} onChange={e=>setColumn(e.target.value)} placeholder="Column optional" className="rounded-lg border px-2 py-1.5 text-xs"/><button type="button" onClick={()=>void onMap(term.id,datasetId,column)} className="rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-bold text-white">Map</button></div>}
