'use client'

import { FormEvent, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { KeyRound, Loader2, ShieldCheck, Trash2, UserRoundCog } from 'lucide-react'

export type ProjectRoleProject={id:string;organizationId:string;name:string}
export type ProjectRoleMember={organizationId:string;userId:string;email:string;organizationRole:string}
export type GovernanceRole={roleKey:string;name:string;description:string|null;capabilities:string[]}
export type ProjectRoleBinding={id:string;projectId:string;userId:string;roleKey:string;active:boolean;assignedAt:string;expiresAt:string|null}

export function ProjectRoleManager({projects,members,roles,bindings}:{projects:ProjectRoleProject[];members:ProjectRoleMember[];roles:GovernanceRole[];bindings:ProjectRoleBinding[]}){
  const router=useRouter();const [projectId,setProjectId]=useState(projects[0]?.id??'');const [userId,setUserId]=useState('');const [roleKey,setRoleKey]=useState(roles[0]?.roleKey??'');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('')
  const project=projects.find(item=>item.id===projectId)
  const projectMembers=useMemo(()=>members.filter(item=>item.organizationId===project?.organizationId),[members,project?.organizationId])
  const activeBindings=useMemo(()=>bindings.filter(item=>item.projectId===projectId&&item.active),[bindings,projectId])
  const emailByUser=useMemo(()=>new Map(members.map(item=>[item.userId,item.email])),[members])
  const roleByKey=useMemo(()=>new Map(roles.map(item=>[item.roleKey,item])),[roles])

  async function call(method:'POST'|'DELETE',body:Record<string,unknown>,key:string){setBusy(key);setMessage('');setError('');try{const response=await fetch('/api/admin/project-roles',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error??'Project role operation failed.');setMessage(method==='POST'?'Governance role assigned.':'Governance role revoked.');if(method==='POST')setUserId('');router.refresh()}catch(e){setError(e instanceof Error?e.message:'Project role operation failed.')}finally{setBusy('')}}
  async function assign(event:FormEvent){event.preventDefault();if(!projectId||!userId||!roleKey)return;await call('POST',{projectId,userId,roleKey},'assign')}

  if(!projects.length)return <div className="rounded-3xl border bg-white p-7 text-sm text-slate-500 shadow-sm">No administrable projects are available.</div>

  return <div className="space-y-6">
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Authorization scope</p><h2 className="mt-1 text-2xl font-black">Governance capability assignment</h2><p className="mt-2 text-sm text-slate-500">Organization membership establishes tenancy. Project governance roles narrow operational responsibilities inside that boundary.</p></div><label className="min-w-72 text-sm font-semibold">Project<select value={projectId} onChange={event=>{setProjectId(event.target.value);setUserId('')}} className="mt-1 w-full rounded-xl border bg-white px-3 py-2.5">{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div></section>
    {message?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{message}</div>:null}{error?<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>:null}
    <section className="grid gap-5 lg:grid-cols-[0.85fr_1.15fr]">
      <form onSubmit={event=>void assign(event)} className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><UserRoundCog className="h-5 w-5 text-blue-600"/><h3 className="text-lg font-black">Assign project role</h3></div><label className="mt-5 block text-sm font-semibold">Organization member<select required value={userId} onChange={event=>setUserId(event.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Select member</option>{projectMembers.map(member=><option key={member.userId} value={member.userId}>{member.email} · {member.organizationRole}</option>)}</select></label><label className="mt-4 block text-sm font-semibold">Governance role<select value={roleKey} onChange={event=>setRoleKey(event.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2.5">{roles.map(role=><option key={role.roleKey} value={role.roleKey}>{role.name}</option>)}</select></label>{roleKey?<div className="mt-4 rounded-2xl bg-slate-50 p-4"><p className="text-sm font-bold">{roleByKey.get(roleKey)?.name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{roleByKey.get(roleKey)?.description}</p><div className="mt-3 flex flex-wrap gap-1.5">{roleByKey.get(roleKey)?.capabilities.map(capability=><span key={capability} className="rounded-full bg-white px-2.5 py-1 text-[11px] font-semibold text-slate-600 ring-1 ring-slate-200">{capability}</span>)}</div></div>:null}<button disabled={busy==='assign'||!userId} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">{busy==='assign'?<Loader2 className="h-4 w-4 animate-spin"/>:<KeyRound className="h-4 w-4"/>}Assign role</button></form>
      <div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-emerald-600"/><h3 className="text-lg font-black">Active project bindings</h3></div><div className="mt-5 space-y-3">{activeBindings.map(binding=>{const role=roleByKey.get(binding.roleKey);return <div key={binding.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{emailByUser.get(binding.userId)??binding.userId}</p><p className="mt-1 text-sm font-semibold text-blue-700">{role?.name??binding.roleKey}</p><p className="mt-1 text-xs text-slate-500">Assigned {new Date(binding.assignedAt).toLocaleString()}</p></div><button type="button" disabled={Boolean(busy)} onClick={()=>void call('DELETE',{projectId,userId:binding.userId,roleKey:binding.roleKey},binding.id)} className="inline-flex items-center gap-1.5 rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-600 hover:bg-red-50 disabled:opacity-40">{busy===binding.id?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Trash2 className="h-3.5 w-3.5"/>}Revoke</button></div><div className="mt-3 flex flex-wrap gap-1.5">{role?.capabilities.slice(0,8).map(capability=><span key={capability} className="rounded-full bg-slate-50 px-2.5 py-1 text-[11px] font-semibold text-slate-500">{capability}</span>)}{(role?.capabilities.length??0)>8?<span className="rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-bold text-blue-600">+{(role?.capabilities.length??0)-8} more</span>:null}</div></div>})}{!activeBindings.length?<p className="rounded-2xl border border-dashed p-6 text-center text-sm text-slate-500">No project-specific governance roles are active. Organization access remains the tenancy boundary.</p>:null}</div></div>
    </section>
  </div>
}
