'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { Activity, Loader2, RefreshCw, ShieldCheck } from 'lucide-react'

type Project={id:string;name:string}
type Scorecard={id?:string;project_id?:string;overall_score:number|string;dimensions:Record<string,number|string>;evidence:Record<string,unknown>;calculated_at?:string}
const surface='rounded-[22px] border border-white/10 bg-[#0a1d33] shadow-[10px_10px_28px_rgba(0,0,0,.22)]'
function percent(value:unknown){const number=Number(value);return Number.isFinite(number)?`${Math.round(number*100)}%`:'N/A'}
function label(key:string){return key.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}
function destination(key:string){const normalized=key.toLowerCase();if(normalized.includes('quality'))return '/data-quality';if(normalized.includes('issue')||normalized.includes('remediation'))return '/issues';if(normalized.includes('catalog')||normalized.includes('dataset')||normalized.includes('owner')||normalized.includes('certif'))return '/catalog';return '/reports'}

export function ScorecardManagerV2({projects}:{projects:Project[]}){
  const [projectId,setProjectId]=useState(projects[0]?.id??'')
  const [scorecard,setScorecard]=useState<Scorecard|null>(null)
  const [history,setHistory]=useState<Scorecard[]>([])
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const selected=useMemo(()=>projects.find(project=>project.id===projectId),[projects,projectId])
  async function load(refresh=false){if(!projectId)return;setBusy(true);setError('');try{const response=await fetch(`/api/scorecards/${encodeURIComponent(projectId)}`,{method:refresh?'POST':'GET'});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error??'Unable to load governance scorecard.');setScorecard(payload.scorecard??null);if(Array.isArray(payload.history))setHistory(payload.history);if(refresh){const historyResponse=await fetch(`/api/scorecards/${encodeURIComponent(projectId)}`);const historyPayload=await historyResponse.json().catch(()=>({}));if(historyResponse.ok&&Array.isArray(historyPayload.history))setHistory(historyPayload.history)}}catch(cause){setError(cause instanceof Error?cause.message:'Unable to load governance scorecard.')}finally{setBusy(false)}}
  useEffect(()=>{void load(false)},[projectId])
  const dimensions=Object.entries(scorecard?.dimensions??{})
  const evidence=Object.entries(scorecard?.evidence??{})

  return <div className="mt-5 space-y-5"><section className={`${surface} flex flex-wrap items-end justify-between gap-4 p-5`}><div><p className="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Evidence-based governance</p><h2 className="mt-1 text-xl font-black text-white">Project scorecard</h2><p className="mt-1 text-sm text-slate-500">Scores are calculated from persisted governance evidence only.</p></div><div className="flex items-end gap-2"><label className="text-xs font-bold text-slate-400">Project<select value={projectId} onChange={event=>setProjectId(event.target.value)} className="mt-1 block min-w-64 rounded-xl border border-white/10 bg-[#07182a] px-3 py-2.5 text-sm text-white">{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><button type="button" onClick={()=>void load(true)} disabled={busy||!projectId} className="inline-flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}Refresh</button></div></section>
    {error?<p className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-300">{error}</p>:null}
    {scorecard?<><section className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><Link href="/reports" className={`${surface} block p-6 transition hover:-translate-y-0.5 hover:border-cyan-400/30`}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-400/10 text-blue-300"><ShieldCheck className="h-5 w-5"/></span><div><p className="text-xs font-bold uppercase text-slate-500">Overall governance score</p><p className="text-5xl font-black text-white">{percent(scorecard.overall_score)}</p></div></div><p className="mt-4 text-xs text-slate-500">{selected?.name??'Project'} · open evidence reports</p></Link><article className={`${surface} p-5`}><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-violet-300"/><h3 className="font-black text-white">Control dimensions</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{dimensions.map(([key,value])=><Link key={key} href={destination(key)} className="rounded-xl border border-white/10 bg-[#08182b] p-4 transition hover:border-cyan-400/30"><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold text-slate-300">{label(key)}</span><span className="text-lg font-black text-white">{percent(value)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-cyan-400" style={{width:`${Math.max(0,Math.min(100,Number(value)*100))}%`}}/></div><p className="mt-2 text-[10px] font-bold text-cyan-300">Open supporting workspace</p></Link>)}</div></article></section>
      <section className={`${surface} p-5`}><div className="flex items-center justify-between"><h3 className="font-black text-white">Evidence register</h3><Link href="/reports" className="text-xs font-bold text-cyan-300">View reports</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{evidence.map(([key,value])=><Link key={key} href={destination(key)} className="rounded-xl border border-white/10 bg-[#08182b] p-4 hover:border-cyan-400/30"><p className="text-xs font-bold uppercase text-slate-500">{label(key)}</p><p className="mt-2 text-2xl font-black text-white">{typeof value==='number'||typeof value==='string'?String(value):JSON.stringify(value)}</p><p className="mt-2 text-[10px] font-bold text-cyan-300">Inspect evidence</p></Link>)}</div></section>
      <section className={`${surface} p-5`}><h3 className="font-black text-white">Recent score history</h3><div className="mt-4 space-y-2">{history.length?history.map((item,index)=><Link key={item.id??index} href="/reports" className="flex items-center justify-between rounded-xl border border-white/10 bg-[#08182b] px-4 py-3 text-sm hover:border-cyan-400/30"><span className="text-slate-500">{item.calculated_at?new Date(item.calculated_at).toLocaleString():`Snapshot ${index+1}`}</span><span className="font-black text-white">{percent(item.overall_score)}</span></Link>):<p className="text-sm text-slate-500">History will accumulate as scorecard refreshes run.</p>}</div></section></>:busy?<section className={`${surface} p-8 text-center text-sm text-slate-500`}><Loader2 className="mx-auto mb-3 h-5 w-5 animate-spin"/>Calculating governance scorecard…</section>:null}
  </div>
}
