'use client'

import { FormEvent, useMemo, useState } from 'react'
import Link from 'next/link'
import { CheckCircle2, GitBranch, Loader2, Plus, RotateCcw, ShieldCheck, Wrench, XCircle } from 'lucide-react'
import { useRouter } from 'next/navigation'

type Project={id:string;name:string;canWorkflowManage:boolean;canIssuesManage:boolean;canQualityRead:boolean}
type Definition={id:string;project_id:string;workflow_key:string;name:string;entity_type:string;version:number;steps:Array<{name:string;capability:string;description?:string|null}>;enabled:boolean}
type Instance={id:string;project_id:string;workflow_definition_id:string;entity_type:string;entity_id:string;status:string;current_step:number;context:Record<string,unknown>;started_at:string;completed_at:string|null;canAct:boolean;activeCapability:string|null}
type Outcome={id:string;project_id:string;workflow_instance_id:string;source_profile_run_id:string;verification_profile_run_id:string|null;remediation_issue_ids:string[]|null;status:string;quality_score_delta:number|string|null;high_severity_findings_delta:number|null;updated_at:string;verified_at:string|null}
type Learning={id:string;project_id:string;workflow_instance_id:string;recommendation_action:string;status:string;effective:boolean|null;quality_score_delta:number|string|null;high_severity_findings_delta:number|null;observed_at:string|null}
type Issue={id:string;project_id:string;profile_run_id:string|null;title:string;status:string;severity:string;updated_at:string}
const capabilityChoices=['policy.approve','certification.review','classification.review','contract.approve','workflow.manage','stewardship.manage','quality.exception.approve']
const surface='rounded-[22px] border border-white/10 bg-[#0a1d33] shadow-[10px_10px_28px_rgba(0,0,0,.22)]'
const input='mt-1 w-full rounded-xl border border-white/10 bg-[#07182a] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400/40'
const short=(value:string|null|undefined)=>value?value.slice(0,8):'pending'

export function WorkflowManagerV2({projects,definitions,instances,outcomes,learning,issues}:{projects:Project[];definitions:Definition[];instances:Instance[];outcomes:Outcome[];learning:Learning[];issues:Issue[]}){
  const router=useRouter()
  const [projectId,setProjectId]=useState(projects[0]?.id??'')
  const project=projects.find(item=>item.id===projectId)
  const [workflowKey,setWorkflowKey]=useState('CERTIFICATION_APPROVAL')
  const [name,setName]=useState('Dataset certification approval')
  const [entityType,setEntityType]=useState('DATASET')
  const [steps,setSteps]=useState([{name:'Steward review',capability:'certification.review',description:'Validate ownership, controls and evidence.'},{name:'Policy approval',capability:'policy.approve',description:'Approve the governed asset for certification.'}])
  const [busy,setBusy]=useState('')
  const [message,setMessage]=useState('')
  const projectDefinitions=definitions.filter(item=>item.project_id===projectId)
  const projectInstances=instances.filter(item=>item.project_id===projectId)
  const outcomeByWorkflow=useMemo(()=>new Map(outcomes.map(item=>[item.workflow_instance_id,item])),[outcomes])
  const projectLearning=learning.filter(item=>item.project_id===projectId)

  async function create(event:FormEvent){event.preventDefault();if(!project?.canWorkflowManage)return;setBusy('create');setMessage('');try{const response=await fetch('/api/workflows/definitions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,workflowKey,name,entityType,steps})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error??'Unable to create workflow.');setMessage(`Workflow ${payload.definition?.workflow_key??workflowKey} v${payload.definition?.version??'?'} created.`);router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'Unable to create workflow.')}finally{setBusy('')}}
  async function act(instanceId:string,action:'APPROVE'|'REJECT'){setBusy(`${action}:${instanceId}`);setMessage('');try{const response=await fetch(`/api/workflows/instances/${instanceId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error??'Unable to update workflow.');setMessage(`Workflow ${action.toLowerCase()} action recorded.`);router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'Unable to update workflow.')}finally{setBusy('')}}
  async function remediation(instanceId:string){if(!project?.canIssuesManage)return;setBusy(`remediate:${instanceId}`);setMessage('');try{const response=await fetch('/api/profiling/remediation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflowInstanceId:instanceId})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error??'Unable to create governed remediation.');setMessage(payload.reusedOutcome?'Existing remediation reused.':`Remediation tracked with ${payload.created?.length??0} new issue(s).`);router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'Unable to create remediation.')}finally{setBusy('')}}
  async function verify(instanceId:string){if(!project?.canQualityRead)return;setBusy(`verify:${instanceId}`);setMessage('');try{const response=await fetch('/api/profiling/remediation/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflowInstanceId:instanceId})});const payload=await response.json().catch(()=>({}));if(!response.ok&&payload.verificationPassed===false){setMessage('Verification completed but did not pass.');router.refresh();return}if(!response.ok)throw new Error(payload.error??'Unable to verify remediation.');setMessage('Remediation verification evidence recorded.');router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'Unable to verify remediation.')}finally{setBusy('')}}
  async function reprofile(instanceId:string){if(!project?.canIssuesManage)return;setBusy(`reprofile:${instanceId}`);setMessage('');try{const response=await fetch('/api/profiling/remediation/reprofile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflowInstanceId:instanceId})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error??'Unable to retry verification.');setMessage(payload.status==='QUEUED'?`Verification profile ${short(payload.profilingRunId)} queued.`:'Verification scheduling checked.');router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'Unable to retry verification.')}finally{setBusy('')}}

  return <div className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
    <div className="space-y-5"><section className={`${surface} p-5`}><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.15em] text-cyan-300">Scope</p><h2 className="mt-1 text-xl font-black text-white">Workflow project</h2></div><ShieldCheck className="h-5 w-5 text-violet-300"/></div><label className="mt-4 block text-xs font-bold text-slate-400">Project<select value={projectId} onChange={event=>{setProjectId(event.target.value);setMessage('')}} className={input}>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[10px] font-bold"><div className={`rounded-xl p-2 ${project?.canWorkflowManage?'bg-emerald-400/10 text-emerald-300':'bg-white/[.04] text-slate-500'}`}>Workflow manage</div><div className={`rounded-xl p-2 ${project?.canIssuesManage?'bg-emerald-400/10 text-emerald-300':'bg-white/[.04] text-slate-500'}`}>Issues manage</div><div className={`rounded-xl p-2 ${project?.canQualityRead?'bg-emerald-400/10 text-emerald-300':'bg-white/[.04] text-slate-500'}`}>Quality verify</div></div></section>
      {project?.canWorkflowManage?<form onSubmit={create} className={`${surface} p-5`}><div className="flex items-center gap-2"><GitBranch className="h-5 w-5 text-violet-300"/><h2 className="font-black text-white">Workflow definition</h2></div><div className="mt-4 grid gap-3"><label className="text-xs font-bold text-slate-400">Workflow key<input value={workflowKey} onChange={event=>setWorkflowKey(event.target.value)} className={input}/></label><label className="text-xs font-bold text-slate-400">Name<input value={name} onChange={event=>setName(event.target.value)} className={input}/></label><label className="text-xs font-bold text-slate-400">Entity type<input value={entityType} onChange={event=>setEntityType(event.target.value.toUpperCase())} className={input}/></label><div><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-400">Approval steps</span><button type="button" onClick={()=>setSteps([...steps,{name:`Step ${steps.length+1}`,capability:'policy.approve',description:''}])} className="text-xs font-bold text-cyan-300">+ Add step</button></div><div className="mt-2 space-y-2">{steps.map((step,index)=><div key={index} className="rounded-xl border border-white/10 bg-[#08182b] p-3"><input value={step.name} onChange={event=>setSteps(steps.map((item,i)=>i===index?{...item,name:event.target.value}:item))} className={input}/><select value={step.capability} onChange={event=>setSteps(steps.map((item,i)=>i===index?{...item,capability:event.target.value}:item))} className={input}>{capabilityChoices.map(capability=><option key={capability}>{capability}</option>)}</select>{steps.length>1?<button type="button" onClick={()=>setSteps(steps.filter((_,i)=>i!==index))} className="mt-2 text-xs font-bold text-rose-300">Remove step</button>:null}</div>)}</div></div><button disabled={busy==='create'} className="inline-flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy==='create'?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>}Create workflow version</button></div></form>:<section className={`${surface} p-5 text-sm text-slate-500`}>Workflow definitions are read-only for this project. `workflow.manage` is required to create a version.</section>}
      {message?<p className="rounded-xl border border-cyan-400/20 bg-cyan-400/10 p-3 text-sm text-cyan-200">{message}</p>:null}
      <section className={`${surface} p-5`}><div className="flex items-center justify-between"><h2 className="font-black text-white">Definitions</h2><span className="text-xs text-slate-500">{projectDefinitions.length}</span></div><div className="mt-3 space-y-2">{projectDefinitions.map(definition=><article key={definition.id} className="rounded-xl border border-white/10 bg-[#08182b] p-3"><p className="font-bold text-slate-200">{definition.name}</p><p className="mt-1 text-xs text-slate-500">{definition.workflow_key} · v{definition.version} · {definition.entity_type}</p><div className="mt-2 flex flex-wrap gap-1">{definition.steps.map((step,index)=><span key={index} className="rounded-lg bg-white/[.05] px-2 py-1 text-[10px] text-slate-400">{index+1}. {step.name}</span>)}</div></article>)}</div></section></div>

    <div className="space-y-5"><section className={`${surface} p-5`}><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.15em] text-violet-300">Active work</p><h2 className="mt-1 text-xl font-black text-white">Workflow instances</h2></div><Link href="/issues" className="text-xs font-bold text-cyan-300">Open issues</Link></div><div className="mt-4 space-y-3">{projectInstances.length?projectInstances.map(instance=>{const outcome=outcomeByWorkflow.get(instance.id);const remediationIds=outcome?.remediation_issue_ids??[];const trackedIssues=issues.filter(issue=>remediationIds.includes(issue.id));return <article key={instance.id} className="rounded-xl border border-white/10 bg-[#08182b] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/workflows?instanceId=${encodeURIComponent(instance.id)}`} className="font-black text-slate-200 hover:text-cyan-300">{instance.entity_type} · {short(instance.entity_id)}</Link><p className="mt-1 text-xs text-slate-500">{instance.status} · step {instance.current_step+1}{instance.activeCapability?` · ${instance.activeCapability}`:''}</p></div><span className="rounded-lg bg-white/[.05] px-2 py-1 text-[10px] font-black text-slate-400">{instance.status}</span></div>{instance.status==='PENDING'&&instance.canAct?<div className="mt-3 flex gap-2"><button onClick={()=>void act(instance.id,'APPROVE')} disabled={busy===`APPROVE:${instance.id}`} className="inline-flex items-center gap-1 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><CheckCircle2 className="h-3.5 w-3.5"/>Approve</button><button onClick={()=>void act(instance.id,'REJECT')} disabled={busy===`REJECT:${instance.id}`} className="inline-flex items-center gap-1 rounded-xl bg-rose-600 px-3 py-2 text-xs font-bold text-white"><XCircle className="h-3.5 w-3.5"/>Reject</button></div>:instance.status==='PENDING'?<p className="mt-3 text-xs text-slate-500">The active step requires {instance.activeCapability??'a capability'} that is not granted for this project.</p>:null}
          {instance.status==='APPROVED'?<div className="mt-3 flex flex-wrap gap-2">{project?.canIssuesManage?<button onClick={()=>void remediation(instance.id)} disabled={busy===`remediate:${instance.id}`} className="inline-flex items-center gap-1 rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-amber-300 hover:bg-white/[.05]"><Wrench className="h-3.5 w-3.5"/>Track remediation</button>:null}{project?.canQualityRead&&outcome?<button onClick={()=>void verify(instance.id)} disabled={busy===`verify:${instance.id}`} className="inline-flex items-center gap-1 rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-cyan-300 hover:bg-white/[.05]"><CheckCircle2 className="h-3.5 w-3.5"/>Verify</button>:null}{project?.canIssuesManage&&outcome?<button onClick={()=>void reprofile(instance.id)} disabled={busy===`reprofile:${instance.id}`} className="inline-flex items-center gap-1 rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-violet-300 hover:bg-white/[.05]"><RotateCcw className="h-3.5 w-3.5"/>Re-profile</button>:null}</div>:null}
          {outcome?<div className="mt-3 grid gap-2 sm:grid-cols-3"><Link href={outcome.source_profile_run_id?`/profiling/explorer?runId=${encodeURIComponent(outcome.source_profile_run_id)}`:'/profiling/explorer'} className="rounded-lg bg-white/[.04] p-2 text-xs text-slate-400 hover:bg-white/[.07]">Source evidence<br/><strong className="text-slate-200">{short(outcome.source_profile_run_id)}</strong></Link><Link href={outcome.verification_profile_run_id?`/profiling/explorer?runId=${encodeURIComponent(outcome.verification_profile_run_id)}`:'/profiling/explorer'} className="rounded-lg bg-white/[.04] p-2 text-xs text-slate-400 hover:bg-white/[.07]">Verification<br/><strong className="text-slate-200">{short(outcome.verification_profile_run_id)}</strong></Link><Link href="/issues" className="rounded-lg bg-white/[.04] p-2 text-xs text-slate-400 hover:bg-white/[.07]">Remediation issues<br/><strong className="text-slate-200">{trackedIssues.length}</strong></Link></div>:null}</article>}).toSorted((a,b)=>Number(b.id===projectInstances[0]?.id)-Number(a.id===projectInstances[0]?.id)):<p className="text-sm text-slate-500">No workflow instances for this project.</p>}</div></section>
      <section className={`${surface} p-5`}><div className="flex items-center justify-between"><h2 className="font-black text-white">Recommendation effectiveness</h2><Link href="/reports" className="text-xs font-bold text-cyan-300">Reports</Link></div><div className="mt-3 space-y-2">{projectLearning.slice(0,12).map(row=><Link key={row.id} href={`/workflows?instanceId=${encodeURIComponent(row.workflow_instance_id)}`} className="flex items-center justify-between rounded-xl border border-white/10 bg-[#08182b] p-3 hover:border-cyan-400/30"><span><span className="block text-sm font-bold text-slate-200">{row.recommendation_action}</span><span className="text-xs text-slate-500">{row.status}</span></span><span className={`text-xs font-black ${row.effective===true?'text-emerald-300':row.effective===false?'text-rose-300':'text-slate-500'}`}>{row.effective===true?'EFFECTIVE':row.effective===false?'INEFFECTIVE':'PENDING'}</span></Link>)}{!projectLearning.length?<p className="text-sm text-slate-500">No recommendation effectiveness evidence yet.</p>:null}</div></section></div>
  </div>
}
