server.port=${PORT:10000}
server.address=0.0.0.0
spring.application.name=datanexus-jdbc-bridge
spring.mvc.problemdetails.enabled=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false
