import { createAdminClient } from '@/lib/supabase/admin'
import { loadFileSource } from '@/lib/profiling/file-source-adapter'

type Row = Record<string, unknown>
type MetricValue = { metric_key: string; numeric_value: number | null; text_value?: string | null; profile_column_id?: string | null }
type ColumnResult = { column_name: string; metrics: MetricValue[]; candidate_key_confidence: number; sensitive_match_rate: number; pattern_match_rate: number | null; finding?: { finding_type: string; severity: 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH'; title: string; description: string; confidence: number; evidence: Record<string, unknown>; recommendation: Record<string, unknown> } }
const RATE_SCALE = 4
function round(value: number, places = RATE_SCALE) { const factor = 10 ** places; return Math.round((value + Number.EPSILON) * factor) / factor }
function isMissing(value: unknown) { return value === null || value === undefined }
function normalized(value: unknown) { return typeof value === 'string' ? value.trim() : value }
function key(value: unknown) { const v = normalized(value); return v === null || v === undefined ? '__NULL__' : typeof v === 'string' ? v : JSON.stringify(v) }
function emailMatch(value: unknown) { return typeof value === 'string' && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim()) }
function sensitiveMatch(columnName: string, value: unknown) { if (isMissing(value)) return false; const name = columnName.toLowerCase(); if (name.includes('email')) return emailMatch(value); if (name.includes('phone') || name.includes('mobile')) return typeof value === 'string' && /^[+()\d\s.-]{7,}$/.test(value.trim()); if (name.includes('ssn') || name.includes('national_id')) return typeof value === 'string' && /^\d{3}-?\d{2}-?\d{4}$/.test(value.trim()); if (name.includes('address')) return typeof value === 'string' && value.trim().length >= 8; return false }
function patternMatch(columnName: string, value: unknown) { if (isMissing(value)) return false; const name = columnName.toLowerCase(); if (name.includes('email')) return emailMatch(value); if (name.includes('phone') || name.includes('mobile')) return typeof value === 'string' && /^[+()\d\s.-]{7,}$/.test(value.trim()); return true }
function calculateColumnMetrics(columnName: string, rows: Row[]): Omit<ColumnResult, 'metrics'> & { metrics: MetricValue[] } {
  const values = rows.map((row) => row[columnName]); const rowCount = values.length; const nullCount = values.filter(isMissing).length; const nonNullValues = values.filter((value) => !isMissing(value)); const distinctCount = new Set(nonNullValues.map(key)).size; const frequencies = new Map<string, number>()
  for (const value of nonNullValues) { const k = key(value); frequencies.set(k, (frequencies.get(k) ?? 0) + 1) }
  const uniqueCount = Array.from(frequencies.values()).filter((count) => count === 1).length; const uniqueRate = nonNullValues.length === 0 ? 0 : uniqueCount / nonNullValues.length; const nullRate = rowCount === 0 ? 0 : nullCount / rowCount; const distinctRate = rowCount === 0 ? 0 : distinctCount / rowCount
  const patternEligible = values.filter((value) => !isMissing(value)); const patternMatchRate = patternEligible.length === 0 ? null : patternEligible.filter((value) => patternMatch(columnName, value)).length / patternEligible.length; const sensitiveMatchRate = patternEligible.length === 0 ? 0 : patternEligible.filter((value) => sensitiveMatch(columnName, value)).length / patternEligible.length; const candidateKeyConfidence = rowCount === 0 ? 0 : round(uniqueRate * (1 - nullRate))
  const metrics: MetricValue[] = [
    { metric_key: 'non_null_count', numeric_value: nonNullValues.length }, { metric_key: 'null_count', numeric_value: nullCount }, { metric_key: 'null_rate', numeric_value: round(nullRate) }, { metric_key: 'distinct_count', numeric_value: distinctCount }, { metric_key: 'distinct_rate', numeric_value: round(distinctRate) }, { metric_key: 'unique_count', numeric_value: uniqueCount }, { metric_key: 'unique_rate', numeric_value: round(uniqueRate) }, { metric_key: 'pattern_match_rate', numeric_value: patternMatchRate === null ? null : round(patternMatchRate) }, { metric_key: 'sensitive_match_rate', numeric_value: round(sensitiveMatchRate) }, { metric_key: 'candidate_key_confidence', numeric_value: candidateKeyConfidence },
  ]
  let finding: ColumnResult['finding']
  if (nullRate > 0.2) {
    finding = { finding_type: 'COMPLETENESS', severity: nullRate >= 0.5 ? 'HIGH' : 'MEDIUM', title: `${columnName} has missing values`, description: `${round(nullRate * 100)}% of observed rows are null or missing.`, confidence: 1, evidence: { null_count: nullCount, row_count: rowCount, null_rate: round(nullRate) }, recommendation: { action: 'review_source_completeness', threshold: 0.2 } }
  } else if (sensitiveMatchRate > 0.8) {
    finding = { finding_type: 'SENSITIVITY', severity: 'INFO', title: `${columnName} appears sensitive`, description: 'Observed values match a known sensitive data pattern.', confidence: round(sensitiveMatchRate), evidence: { sensitive_match_rate: round(sensitiveMatchRate) }, recommendation: { action: 'apply_data_classification_and_access_controls' } }
  }
  return { column_name: columnName, metrics, candidate_key_confidence: candidateKeyConfidence, sensitive_match_rate: round(sensitiveMatchRate), pattern_match_rate: patternMatchRate === null ? null : round(patternMatchRate), finding }
}
async function loadRowsFromTable(supabase: ReturnType<typeof createAdminClient>, datasetVersionId: string, maxRows: number) {
  const { data: source, error: sourceError } = await supabase.rpc('get_dataset_execution_source', { p_dataset_version_id: datasetVersionId })
  if (!sourceError && source) { const sourceType = String(source.source_type ?? '').trim().toLowerCase(); const executionConfig = source.execution_config && typeof source.execution_config === 'object' ? source.execution_config as Record<string, unknown> : {}; if (sourceType === 'file') { const loaded = await loadFileSource(supabase, { sourceUri: source.source_uri, executionConfig }, { maxRows }); return { rowCount: loaded.rowCount, rows: loaded.rows as Row[], sourceAccess: { source_type: 'FILE', source_uri: loaded.sourceUri, content_hash: loaded.contentHash, sampled_rows: loaded.rows.length, warnings: loaded.warnings } } } }
  const { data: version, error: versionError } = await supabase.rpc('get_dataset_version_for_profiling', { dataset_version_id: datasetVersionId }); if (versionError) throw new Error(`Unable to resolve dataset version: ${versionError.message}`)
  const dataset = Array.isArray(version?.datasets) ? version.datasets[0] : version?.datasets; const dataSource = Array.isArray(dataset?.data_sources) ? dataset.data_sources[0] : dataset?.data_sources; const sourceType = String(dataSource?.source_type ?? '').toLowerCase(); const metadata = dataSource?.connection_metadata ?? {}; const table = metadata.table ?? metadata.table_name ?? metadata.tableName; const schema = metadata.schema ?? metadata.schema_name ?? metadata.schemaName ?? 'public'
  if (!['supabase', 'supabase_table', 'postgres', 'postgres_table', 'table'].includes(sourceType) || !table) { if (sourceError) throw new Error(`Unable to resolve execution source for dataset version ${datasetVersionId}: ${sourceError.message}`); throw new Error(`No executable source is configured for dataset version ${datasetVersionId}. FILE sources require execution_config.url or execution_config.bucket + execution_config.path.`) }
  const { count, error: countError } = await supabase.schema(schema).from(table).select('*', { count: 'exact', head: true }); if (countError) throw new Error(`Unable to count source rows: ${countError.message}`)
  const { data, error } = await supabase.schema(schema).from(table).select('*').range(0, maxRows - 1); if (error) throw new Error(`Unable to load source rows: ${error.message}`); return { rowCount: count ?? 0, rows: (data ?? []) as Row[] }
}
export async function executeProfilingMetrics(datasetVersionId: string, profilingRunId: string, input: Record<string, unknown> = {}) {
  const supabase = createAdminClient(); const { data: activeRun, error: activeRunError } = await supabase.schema('profiling').from('profile_runs').select('id, dataset_version_id, status, summary').eq('id', profilingRunId).maybeSingle(); if (activeRunError) throw new Error(`Unable to verify profiling run: ${activeRunError.message}`); if (!activeRun) throw new Error(`Profiling run ${profilingRunId} was not found.`); if (activeRun.dataset_version_id !== datasetVersionId) throw new Error(`Profiling run ${profilingRunId} does not belong to dataset version ${datasetVersionId}.`); if (activeRun.status === 'CANCELLED') throw new Error(`Profiling run ${profilingRunId} has been cancelled.`)
  const inputRows = Array.isArray(input.rows) ? input.rows.filter((row): row is Row => !!row && typeof row === 'object' && !Array.isArray(row)) : null; const loaded = inputRows ? { rowCount: inputRows.length, rows: inputRows } : await loadRowsFromTable(supabase, datasetVersionId, 1000); const rows = loaded.rows; const columnNames = Array.from(new Set(rows.flatMap((row) => Object.keys(row))))
  const metricKeys = ['column_count', 'row_count', 'non_null_count', 'null_count', 'null_rate', 'distinct_count', 'distinct_rate', 'unique_count', 'unique_rate', 'pattern_match_rate', 'sensitive_match_rate', 'candidate_key_confidence']
  const { data: definitions, error: definitionError } = await supabase.schema('profiling').from('metric_definitions').select('id, metric_key, scope, enabled').in('metric_key', metricKeys); if (definitionError) throw new Error(`Unable to load metric definitions: ${definitionError.message}`)
  const definitionByKey = new Map((definitions ?? []).map((definition) => [definition.metric_key, definition])); for (const key of metricKeys) { const definition = definitionByKey.get(key); if (!definition?.enabled) throw new Error(`Metric definition contract violation: enabled definition missing for ${key}.`) }
  const results = columnNames.map((columnName) => calculateColumnMetrics(columnName, rows))
  const { data: profileColumns, error: columnsError } = await supabase.schema('profiling').from('profile_columns').select('id, column_name').eq('profile_run_id', profilingRunId); if (columnsError) throw new Error(`Unable to load profile columns: ${columnsError.message}`)
  const columnIdByName = new Map((profileColumns ?? []).map((column) => [column.column_name, column.id])); if (columnNames.some((name) => !columnIdByName.has(name))) throw new Error(`Profile column contract violation for run ${profilingRunId}: source columns are not fully registered.`)
  const { error: metricDeleteError } = await supabase.schema('profiling').from('profile_metrics').delete().eq('profile_run_id', profilingRunId); if (metricDeleteError) throw new Error(`Unable to clear previous profile metrics: ${metricDeleteError.message}`)
  const { error: findingDeleteError } = await supabase.schema('profiling').from('profile_findings').delete().eq('profile_run_id', profilingRunId); if (findingDeleteError) throw new Error(`Unable to clear previous profile findings: ${findingDeleteError.message}`)
  const metricRows = results.flatMap((result) => result.metrics.map((metric) => { const definition = definitionByKey.get(metric.metric_key); if (!definition || definition.scope !== 'COLUMN') throw new Error(`Metric definition contract violation for ${metric.metric_key}: expected enabled COLUMN definition.`); return { profile_run_id: profilingRunId, metric_definition_id: definition.id, profile_column_id: columnIdByName.get(result.column_name)!, metric_key: metric.metric_key, numeric_value: metric.numeric_value } }))
  const datasetMetrics = ['column_count', 'row_count'].map((metric_key) => { const definition = definitionByKey.get(metric_key); if (!definition || definition.scope !== 'DATASET') throw new Error(`Metric definition contract violation for ${metric_key}: expected enabled DATASET definition.`); return { profile_run_id: profilingRunId, metric_definition_id: definition.id, profile_column_id: null, metric_key, numeric_value: metric_key === 'column_count' ? columnNames.length : loaded.rowCount } })
  const allMetricRows = [...datasetMetrics, ...metricRows]; if (allMetricRows.length) { const { error } = await supabase.schema('profiling').from('profile_metrics').insert(allMetricRows); if (error) throw new Error(`Unable to persist profile metrics: ${error.message}`) }
  const findings = results.filter((result) => result.finding).map((result) => ({ profile_run_id: profilingRunId, profile_column_id: columnIdByName.get(result.column_name)!, ...result.finding })); if (findings.length) { const { error } = await supabase.schema('profiling').from('profile_findings').insert(findings); if (error) throw new Error(`Unable to persist profile findings: ${error.message}`) }
  const completeness = results.length === 0 ? 0 : results.reduce((sum, result) => sum + (1 - (result.metrics.find((item) => item.metric_key === 'null_rate')?.numeric_value ?? 1)), 0) / results.length; const uniqueness = results.length === 0 ? 0 : results.reduce((sum, result) => sum + (result.metrics.find((item) => item.metric_key === 'unique_rate')?.numeric_value ?? 0), 0) / results.length; const validityCandidates = results.map((result) => result.pattern_match_rate).filter((value): value is number => value !== null); const validity = validityCandidates.length ? validityCandidates.reduce((sum, value) => sum + value, 0) / validityCandidates.length : 1; const scorePayload = { completeness_score: round(completeness), uniqueness_score: round(uniqueness), validity_score: round(validity), accuracy_score: null, overall_score: round((completeness + uniqueness + validity) / 3), scoring_basis: 'deterministic_metrics' }
  const { error: scoreError } = await supabase.schema('profiling').from('data_quality_scores').upsert({ profile_run_id: profilingRunId, completeness_score: scorePayload.completeness_score, uniqueness_score: scorePayload.uniqueness_score, validity_score: scorePayload.validity_score, accuracy_score: null, overall_score: scorePayload.overall_score }, { onConflict: 'profile_run_id' }); if (scoreError) throw new Error(`Unable to persist quality score: ${scoreError.message}`)
  const existingSummary = activeRun.summary && typeof activeRun.summary === 'object' && !Array.isArray(activeRun.summary) ? activeRun.summary as Record<string, unknown> : {}; const baseSummary = { ...existingSummary, metric_engine: 'deterministic', sample_size: rows.length, score: scorePayload, source_access: 'sourceAccess' in loaded ? loaded.sourceAccess : { source_type: 'TABLE' } }
  const { data: updatedRun, error: runUpdateError } = await supabase.schema('profiling').from('profile_runs').update({ row_count: loaded.rowCount, column_count: columnNames.length, summary: baseSummary }).eq('id', profilingRunId).eq('dataset_version_id', datasetVersionId).neq('status', 'CANCELLED').select('id').maybeSingle(); if (runUpdateError) throw new Error(`Unable to persist profiling run summary: ${runUpdateError.message}`); if (!updatedRun) throw new Error(`Profiling run ${profilingRunId} was cancelled or changed while metrics were executing.`)
  return { tool: 'execute_metrics', status: 'COMPLETED', dataset_version_id: datasetVersionId, profiling_run_id: profilingRunId, row_count: loaded.rowCount, column_count: columnNames.length, metrics_persisted: allMetricRows.length, findings_persisted: findings.length, score: scorePayload, source_access: 'sourceAccess' in loaded ? loaded.sourceAccess : { source_type: 'TABLE' }, columns: results }
}
