-- Synthetic governance knowledge corpus for AI-governance validation.
-- Public references inform concepts only; seeded text is original and explicitly non-authoritative.

with p as (
  select id project_id from app.projects where name='Profiling Demo Project' order by created_at limit 1
), docs(document_key,document_type,title,summary,content,domain,jurisdiction,source_kind,source_url,metadata) as (values
('SYN-GUIDE-GLOSSARY','GUIDANCE','Business Glossary Operating Guide','Synthetic operating guide for terms, definitions, synonyms and domains.','Business glossary terms must have a clear business definition, domain and lifecycle status. Synonyms may improve discovery but must not replace the approved canonical term. Mappings from terms to datasets or columns are suggestions until approved. Conflicting definitions should be surfaced to a steward rather than silently merged.','Governance','Global','SYNTHETIC',null,'{"synthetic_bootstrap":true,"knowledge_domain":"Business glossary"}'::jsonb),
('EXT-REG-GDPR','REGULATION','GDPR Applicability Reference','Governance reference summarising selected GDPR applicability concepts for synthetic customer data.','This reference records that Regulation (EU) 2016/679 governs processing of personal data in relevant EU and EEA contexts. The platform models applicability, purpose limitation, minimisation, accuracy, storage limitation, security and accountability as governance concepts. Exact legal applicability must be determined by qualified organizational stakeholders; this synthetic reference is not legal advice.','Privacy','EU/EEA','EXTERNAL_REFERENCE','https://eur-lex.europa.eu/eli/reg/2016/679/oj','{"synthetic_bootstrap":true,"knowledge_domain":"Regulations","not_legal_advice":true,"research_basis":["EUR-Lex Regulation EU 2016/679","EDPB GDPR principles"]}'::jsonb),
('SYN-STD-CLASSIFICATION','STANDARD','Enterprise Data Classification Standard','Synthetic standard for PII, PCI, confidential and restricted classifications.','Data must be classified according to sensitivity and handling risk. PII identifies or relates to individuals, PCI covers payment card account or authentication data, Confidential covers sensitive internal information whose unauthorized disclosure may materially harm the organization, and Restricted covers the highest sensitivity information requiring strict need-to-know controls. AI may recommend classifications with confidence and evidence; authorized human approval establishes authoritative status.','Governance','Global','SYNTHETIC','https://www.pcisecuritystandards.org/standards/pci-dss/','{"synthetic_bootstrap":true,"knowledge_domain":"Classifications","research_basis":["PCI DSS overview","NIST Privacy Framework","NIST CSF 2.0"]}'::jsonb),
('SYN-STD-OWNERSHIP','STANDARD','Data Ownership and Stewardship Standard','Synthetic standard for business owner, technical owner and steward accountability.','Each governed dataset and critical data element must have accountable roles. The Business Owner is accountable for business use and priority, the Technical Owner is accountable for technical operation and source integrity, and the Data Steward is responsible for definitions, classifications, quality follow-up, certification evidence and governance issue coordination. Role assignments may later be bound to named users through organization-specific workflows.','Governance','Global','SYNTHETIC','https://www.nist.gov/cyberframework','{"synthetic_bootstrap":true,"knowledge_domain":"Ownership and Stewardship","research_basis":["NIST CSF 2.0 governance roles and responsibilities"]}'::jsonb),
('SYN-STD-DATA-CONTRACT','STANDARD','Data Contract and SLA Standard','Synthetic standard for versioned data expectations and service levels.','A data contract must identify the governed dataset, compatibility policy, critical columns, quality expectations and freshness service level. Contract versions are immutable historical agreements once active. Material schema or SLA changes require a new version and impact review. Violations should be evaluated using profiling and DQ evidence and linked to downstream consumers where lineage is available.','Governance','Global','SYNTHETIC',null,'{"synthetic_bootstrap":true,"knowledge_domain":"Data contracts"}'::jsonb),
('SYN-STD-CERTIFICATION','STANDARD','Dataset Certification Standard','Synthetic standard for certified, provisional and expired states.','Certification represents an evidence-based governance decision. CERTIFIED means required ownership, quality, classification and contract evidence is currently acceptable. PROVISIONAL means the asset is usable with documented gaps and an expiry or review date. EXPIRED means prior certification is no longer current. Certification must retain evidence and decision rationale.','Governance','Global','SYNTHETIC',null,'{"synthetic_bootstrap":true,"knowledge_domain":"Certifications"}'::jsonb),
('SYN-PLAYBOOK-INCIDENT','PROCEDURE','Governance Issue and Incident Knowledge Playbook','Synthetic playbook for prior problems, root causes, impact and outcomes.','Governance issues and incidents should retain the observed symptom, severity, affected asset, evidence, probable root cause, business impact, recommended action and resolution outcome. Resolved cases are reusable investigation evidence when a later problem is similar. AI may propose similarity and likely cause, but evidence and confidence must be visible.','Operations','Global','SYNTHETIC','https://www.nist.gov/cyberframework','{"synthetic_bootstrap":true,"knowledge_domain":"Issues/incidents","research_basis":["NIST CSF 2.0 detect/respond concepts"]}'::jsonb),
('SYN-GUIDE-REMEDIATION','GUIDANCE','Remediation Knowledge and Learning Guide','Synthetic guide for capturing what worked and what failed.','Every material remediation should capture the initial symptom, action taken, before evidence, after evidence and outcome status. WORKED outcomes can become reusable recommendations for similar cases. PARTIAL outcomes require qualification. FAILED outcomes are negative knowledge and should reduce confidence in repeating the same action under similar conditions.','Governance','Global','SYNTHETIC',null,'{"synthetic_bootstrap":true,"knowledge_domain":"Remediation knowledge"}'::jsonb))
insert into governance.knowledge_documents(project_id,document_key,document_type,title,summary,content,domain,jurisdiction,status,effective_at,source_kind,source_url,content_hash,metadata)
select p.project_id,d.document_key,d.document_type,d.title,d.summary,d.content,d.domain,d.jurisdiction,'ACTIVE',now(),d.source_kind,d.source_url,encode(digest(d.content,'sha256'),'hex'),d.metadata from p cross join docs d
on conflict(project_id,document_key) do update set document_type=excluded.document_type,title=excluded.title,summary=excluded.summary,content=excluded.content,domain=excluded.domain,jurisdiction=excluded.jurisdiction,source_kind=excluded.source_kind,source_url=excluded.source_url,content_hash=excluded.content_hash,metadata=excluded.metadata,updated_at=now();

with p as (select id project_id from app.projects where name='Profiling Demo Project' order by created_at limit 1), labels(code,name,category,description,handling) as (values
('CONFIDENTIAL','Confidential','CONFIDENTIAL','Sensitive internal or business information whose unauthorized disclosure could materially harm the organization.','{"access":"restricted","sharing":"approved_channels_only","encryption":"recommended"}'::jsonb),
('RESTRICTED','Restricted','CONFIDENTIAL','Highest-sensitivity business information requiring strict need-to-know access and strong protection.','{"access":"strict_need_to_know","masking":"required_when_feasible","encryption":"required","audit":"required"}'::jsonb),
('INTERNAL','Internal','INTERNAL','Non-public organizational information intended for internal business use.','{"access":"workforce_or_approved_partners"}'::jsonb))
insert into governance.classification_labels(project_id,code,name,category,description,handling_requirements,enabled)
select p.project_id,l.code,l.name,l.category,l.description,l.handling,true from p cross join labels l
where not exists(select 1 from governance.classification_labels x where x.project_id=p.project_id and x.code=l.code);
