with p as (select id project_id from app.projects where name='Profiling Demo Project' order by created_at limit 1), reqs(document_key,requirement_key,title,requirement_text,obligation_type,priority) as (values
('EXT-REG-GDPR','GDPR-APPL-01','Personal-data applicability review','Customer data proposed as personal information requires an applicability review considering processing purpose, jurisdiction and organizational role before authoritative legal applicability is set.','PRINCIPLE','CRITICAL'),
('SYN-STD-CLASSIFICATION','CLASS-01','Classification evidence and approval','Sensitive-data classifications generated by AI must include confidence and evidence and remain suggested until authorized approval.','CONTROL','HIGH'),
('SYN-STD-OWNERSHIP','OWN-01','Business owner accountability','Each critical data domain or element must have an accountable business owner role.','CONTROL','HIGH'),
('SYN-STD-OWNERSHIP','OWN-02','Steward accountability','Each critical governed dataset or CDE must have a steward role responsible for definitions, classifications and quality follow-up.','CONTROL','HIGH'),
('SYN-STD-DATA-CONTRACT','CONTRACT-01','Versioned quality and freshness expectations','Data contracts must version quality requirements, critical columns and freshness service levels.','CONTROL','HIGH'),
('SYN-STD-CERTIFICATION','CERT-01','Evidence-based certification','Certification status must be supported by current ownership, quality, classification and contract evidence.','EVIDENCE','HIGH'),
('SYN-PLAYBOOK-INCIDENT','INC-01','Reusable incident evidence','Resolved incidents must retain symptom, probable cause, impact, recommendation and outcome for future investigations.','EVIDENCE','HIGH'),
('SYN-GUIDE-REMEDIATION','REM-01','Outcome-based remediation learning','Remediation guidance must distinguish worked, partial and failed outcomes using before-and-after evidence.','EVIDENCE','HIGH'))
insert into governance.knowledge_requirements(project_id,document_id,requirement_key,title,requirement_text,obligation_type,priority,metadata)
select p.project_id,d.id,r.requirement_key,r.title,r.requirement_text,r.obligation_type,r.priority,jsonb_build_object('synthetic_bootstrap',true,'knowledge_graph',true)
from p cross join reqs r join governance.knowledge_documents d on d.project_id=p.project_id and d.document_key=r.document_key
on conflict(project_id,requirement_key) do update set title=excluded.title,requirement_text=excluded.requirement_text,obligation_type=excluded.obligation_type,priority=excluded.priority,metadata=excluded.metadata,updated_at=now();

with p as (select id project_id from app.projects where name='Profiling Demo Project' order by created_at limit 1),d as (select id dataset_id from catalog.datasets where project_id=(select project_id from p) and name='Customer 2nd Master' order by created_at limit 1),rels(source_type,source_key,relationship_type,target_type,target_key,confidence) as (values
('REGULATION','EXT-REG-GDPR','DRIVES_POLICY','POLICY','SYN-POL-PERSONAL-DATA',0.98::numeric),
('POLICY','SYN-POL-PERSONAL-DATA','IMPLEMENTED_BY_CONTROL','CONTROL','PD-04',0.99),
('CONTROL','PD-04','GOVERNS_TERM','BUSINESS_TERM','Customer Email Address',0.99),
('BUSINESS_TERM','Customer Email Address','DEFINES_CDE','CDE','CUSTOMER_EMAIL',0.99),
('CDE','CUSTOMER_EMAIL','MAPPED_TO_DATASET','DATASET',(select dataset_id::text from d),0.99),
('DATASET',(select dataset_id::text from d),'HAS_COLUMN','COLUMN',(select dataset_id::text from d)||':email',1.0),
('COLUMN',(select dataset_id::text from d)||':email','MONITORED_BY_RULE','DQ_RULE','CUSTOMER_EMAIL_VALIDITY',0.99),
('DQ_RULE','CUSTOMER_EMAIL_VALIDITY','ACCOUNTABLE_TO','OWNER_ROLE','ROLE:CUSTOMER_DATA_OWNER',1.0),
('DQ_RULE','CUSTOMER_EMAIL_VALIDITY','STEWARDED_BY','STEWARD_ROLE','ROLE:CUSTOMER_DATA_STEWARD',1.0),
('REGULATION','EXT-REG-GDPR','HAS_APPLICABILITY_CONTROL','CONTROL','GDPR-APPL-01',1.0),
('POLICY','SYN-POL-PERSONAL-DATA','REQUIRES_CLASSIFICATION_CONTROL','CONTROL','CLASS-01',0.95),
('CONTROL','CLASS-01','CLASSIFIES_CDE','CDE','CUSTOMER_EMAIL',0.99),
('CDE','CUSTOMER_EMAIL','CLASSIFIED_AS','CLASSIFICATION','PII',0.99),
('CDE','CUSTOMER_ID','MAPPED_TO_DATASET','DATASET',(select dataset_id::text from d),0.99),
('DATASET',(select dataset_id::text from d),'HAS_COLUMN','COLUMN',(select dataset_id::text from d)||':customer_id',1.0),
('COLUMN',(select dataset_id::text from d)||':customer_id','MONITORED_BY_RULE','DQ_RULE','CUST_ID_COMPLETENESS',1.0),
('COLUMN',(select dataset_id::text from d)||':customer_id','MONITORED_BY_RULE','DQ_RULE','CUST_ID_UNIQUENESS',1.0),
('DATASET',(select dataset_id::text from d),'GOVERNED_BY_CONTRACT','DATA_CONTRACT','Customer Master Data Contract',1.0),
('DATA_CONTRACT','Customer Master Data Contract','IMPLEMENTS_CONTROL','CONTROL','CONTRACT-01',1.0),
('DATASET',(select dataset_id::text from d),'HAS_CERTIFICATION','CERTIFICATION','SYN-CERT-CUSTOMER-MASTER',1.0),
('CERTIFICATION','SYN-CERT-CUSTOMER-MASTER','EVIDENCED_BY_CONTROL','CONTROL','CERT-01',0.98),
('DATASET',(select dataset_id::text from d),'OWNED_BY','OWNER_ROLE','ROLE:CUSTOMER_DATA_OWNER',1.0),
('DATASET',(select dataset_id::text from d),'TECHNICALLY_OWNED_BY','OWNER_ROLE','ROLE:CUSTOMER_PLATFORM_OWNER',1.0),
('DATASET',(select dataset_id::text from d),'STEWARDED_BY','STEWARD_ROLE','ROLE:CUSTOMER_DATA_STEWARD',1.0),
('ISSUE','Synthetic historical duplicate customer identifier issue','AFFECTS','DATASET',(select dataset_id::text from d),1.0),
('ISSUE','Synthetic historical duplicate customer identifier issue','RESOLVED_BY','REMEDIATION_KNOWLEDGE','REM-CUSTOMER-ID-DUPLICATES',0.98),
('REMEDIATION_KNOWLEDGE','REM-CUSTOMER-ID-DUPLICATES','IMPLEMENTS_CONTROL','CONTROL','DQ-02',0.96),
('INCIDENT','Synthetic customer freshness delay incident','AFFECTS','DATASET',(select dataset_id::text from d),1.0),
('INCIDENT','Synthetic customer freshness delay incident','RECOMMENDS_CONTROL','CONTROL','CONTRACT-01',0.90),
('CONTROL','OWN-01','ASSIGNS','OWNER_ROLE','ROLE:CUSTOMER_DATA_OWNER',1.0),
('CONTROL','OWN-02','ASSIGNS','STEWARD_ROLE','ROLE:CUSTOMER_DATA_STEWARD',1.0))
insert into governance.knowledge_relationships(project_id,source_type,source_key,relationship_type,target_type,target_key,confidence,status,evidence,metadata)
select p.project_id,r.source_type,r.source_key,r.relationship_type,r.target_type,r.target_key,r.confidence,'ACTIVE',jsonb_build_object('synthetic_bootstrap',true,'knowledge_graph',true),jsonb_build_object('source','FULL_DOMAIN_BOOTSTRAP') from p cross join rels r
on conflict(project_id,source_type,source_key,relationship_type,target_type,target_key) do update set confidence=excluded.confidence,status='ACTIVE',evidence=excluded.evidence,metadata=excluded.metadata,updated_at=now();

create or replace function governance.traverse_knowledge_graph(
  p_project_id uuid,
  p_anchor_type text,
  p_anchor_key text,
  p_direction text default 'BOTH',
  p_max_depth integer default 4,
  p_max_edges integer default 200
) returns table(
  depth integer,
  edge_id uuid,
  source_type text,
  source_key text,
  relationship_type text,
  target_type text,
  target_key text,
  confidence numeric,
  evidence jsonb,
  metadata jsonb
)
language sql stable security invoker set search_path='' as $$
with recursive oriented as (
  select r.id,r.source_type,r.source_key,r.relationship_type,r.target_type,r.target_key,r.confidence,r.evidence,r.metadata
  from governance.knowledge_relationships r
  where r.project_id=p_project_id and r.status='ACTIVE' and upper(coalesce(p_direction,'BOTH')) in ('DOWNSTREAM','BOTH')
  union all
  select r.id,r.target_type,r.target_key,r.relationship_type,r.source_type,r.source_key,r.confidence,r.evidence,r.metadata||jsonb_build_object('reversed',true)
  from governance.knowledge_relationships r
  where r.project_id=p_project_id and r.status='ACTIVE' and upper(coalesce(p_direction,'BOTH')) in ('UPSTREAM','BOTH')
), walk(depth,edge_id,source_type,source_key,relationship_type,target_type,target_key,confidence,evidence,metadata,path) as (
  select 1,o.id,o.source_type,o.source_key,o.relationship_type,o.target_type,o.target_key,o.confidence,o.evidence,o.metadata,
    array[o.source_type||':'||o.source_key,o.target_type||':'||o.target_key]
  from oriented o
  where o.source_type=upper(trim(p_anchor_type)) and o.source_key=p_anchor_key
  union all
  select w.depth+1,o.id,o.source_type,o.source_key,o.relationship_type,o.target_type,o.target_key,o.confidence,o.evidence,o.metadata,
    w.path||(o.target_type||':'||o.target_key)
  from walk w join oriented o on o.source_type=w.target_type and o.source_key=w.target_key
  where w.depth < greatest(1,least(coalesce(p_max_depth,4),8))
    and not ((o.target_type||':'||o.target_key)=any(w.path))
), dedup as (
  select distinct on (edge_id,source_type,source_key,target_type,target_key)
    depth,edge_id,source_type,source_key,relationship_type,target_type,target_key,confidence,evidence,metadata
  from walk
  order by edge_id,source_type,source_key,target_type,target_key,depth
)
select d.depth,d.edge_id,d.source_type,d.source_key,d.relationship_type,d.target_type,d.target_key,d.confidence,d.evidence,d.metadata
from dedup d
order by d.depth,d.source_type,d.source_key,d.relationship_type,d.target_type,d.target_key
limit greatest(1,least(coalesce(p_max_edges,200),400));
$$;

grant execute on function governance.traverse_knowledge_graph(uuid,text,text,text,integer,integer) to authenticated,service_role;
