with p as (select id project_id from app.projects where name='Profiling Demo Project' order by created_at limit 1),d as (select id dataset_id from catalog.datasets where project_id=(select project_id from p) and name='Customer 2nd Master' order by created_at limit 1),reg as (select id from governance.knowledge_documents where project_id=(select project_id from p) and document_key='EXT-REG-GDPR')
insert into governance.regulatory_applicability(project_id,regulation_document_id,scope_type,scope_key,applicability_status,rationale,evidence,metadata)
select p.project_id,reg.id,'DATASET',d.dataset_id::text,'REVIEW_REQUIRED','The synthetic customer dataset contains fields proposed as personal information. Organizational context, processing purpose, jurisdiction and legal basis must be confirmed before authoritative applicability is set.',jsonb_build_object('synthetic_bootstrap',true,'candidate_personal_fields',array['customer_id','full_name','email','country','age']),jsonb_build_object('not_legal_advice',true) from p join d on true join reg on true
on conflict(project_id,regulation_document_id,scope_type,scope_key) do update set applicability_status='REVIEW_REQUIRED',rationale=excluded.rationale,evidence=excluded.evidence,metadata=excluded.metadata,updated_at=now();

with p as (select id project_id from app.projects where name='Profiling Demo Project' order by created_at limit 1),d as (select id dataset_id from catalog.datasets where project_id=(select project_id from p) and name='Customer 2nd Master' order by created_at limit 1)
insert into governance.issues(project_id,dataset_id,title,description,severity,status,resolution_summary,resolution_evidence,created_at,updated_at,resolved_at)
select p.project_id,d.dataset_id,'Synthetic historical duplicate customer identifier issue','Historical training case: duplicate customer identifiers were observed after an upstream merge process did not enforce the authoritative-key rule.','HIGH','RESOLVED','The merge logic was corrected, duplicate records were reconciled, and identifier uniqueness monitoring was added.',jsonb_build_object('synthetic_bootstrap',true,'outcome','WORKED','lesson','Enforce authoritative key selection before merge and monitor distinct rate.'),now()-interval '60 days',now()-interval '55 days',now()-interval '55 days' from p join d on true
where not exists(select 1 from governance.issues i where i.project_id=p.project_id and i.title='Synthetic historical duplicate customer identifier issue');

with p as (select id project_id from app.projects where name='Profiling Demo Project' order by created_at limit 1),d as (select id dataset_id from catalog.datasets where project_id=(select project_id from p) and name='Customer 2nd Master' order by created_at limit 1)
insert into governance.observability_incidents(project_id,dataset_id,status,severity,title,summary,probable_root_causes,business_impact,risk,recommendations,confidence,approval_required,evidence,first_observed_at,last_observed_at,resolved_at,created_at,updated_at)
select p.project_id,d.dataset_id,'RESOLVED','MEDIUM','Synthetic customer freshness delay incident','Historical training incident: customer master delivery arrived later than its expected daily freshness window.','[{"cause":"upstream batch start delayed","confidence":0.88}]'::jsonb,'Customer service and analytics consumers received stale customer status for part of the business day.','{"likelihood":"medium","impact":"medium"}'::jsonb,'[{"action":"add upstream freshness alert"},{"action":"monitor contract freshness SLA"}]'::jsonb,0.88,false,jsonb_build_object('synthetic_bootstrap',true,'outcome','WORKED'),now()-interval '45 days',now()-interval '44 days',now()-interval '44 days',now()-interval '45 days',now()-interval '44 days' from p join d on true
where not exists(select 1 from governance.observability_incidents x where x.project_id=p.project_id and x.title='Synthetic customer freshness delay incident');

with p as (select id project_id from app.projects where name='Profiling Demo Project' order by created_at limit 1),d as (select id dataset_id from catalog.datasets where project_id=(select project_id from p) and name='Customer 2nd Master' order by created_at limit 1),i as (select id issue_id from governance.issues where project_id=(select project_id from p) and title='Synthetic historical duplicate customer identifier issue' order by created_at limit 1),knowledge(knowledge_key,problem_type,symptom,action,outcome,before_evidence,after_evidence,guidance,confidence,issue_link) as (values
('REM-CUSTOMER-ID-DUPLICATES','DUPLICATE_IDENTIFIER','Customer identifier distinct rate deteriorates or duplicate identifiers are observed.','Correct upstream merge key selection, reconcile duplicates, then add identifier uniqueness monitoring.','WORKED','{"duplicate_identifier_condition":true}'::jsonb,'{"duplicate_identifier_condition":false,"monitoring_added":true}'::jsonb,'For customer-master merges, confirm the authoritative identifier before merging and retain a distinct-rate DQ rule after remediation.',0.94::numeric,true),
('REM-RELAX-COMPLETENESS-THRESHOLD','MISSING_CRITICAL_IDENTIFIER','Critical customer identifiers are missing.','Relax the completeness threshold to suppress alerts without fixing source records.','FAILED','{"critical_identifier_missing":true}'::jsonb,'{"critical_identifier_missing":true,"alerts_reduced_only":true}'::jsonb,'Do not treat threshold relaxation as remediation for missing critical identifiers unless there is an approved documented exception. Prefer source correction or governed exception handling.',0.97,false))
insert into governance.remediation_knowledge(project_id,dataset_id,issue_id,knowledge_key,problem_type,symptom,remediation_action,outcome_status,before_evidence,after_evidence,reusable_guidance,confidence,metadata)
select p.project_id,d.dataset_id,case when k.issue_link then i.issue_id else null end,k.knowledge_key,k.problem_type,k.symptom,k.action,k.outcome,k.before_evidence,k.after_evidence,k.guidance,k.confidence,jsonb_build_object('synthetic_bootstrap',true,'knowledge_source','SYN-GUIDE-REMEDIATION') from p join d on true left join i on true cross join knowledge k
on conflict(project_id,knowledge_key) do update set problem_type=excluded.problem_type,symptom=excluded.symptom,remediation_action=excluded.remediation_action,outcome_status=excluded.outcome_status,before_evidence=excluded.before_evidence,after_evidence=excluded.after_evidence,reusable_guidance=excluded.reusable_guidance,confidence=excluded.confidence,metadata=excluded.metadata,updated_at=now();
