create table if not exists orchestration.projection_outbox (
  sequence_id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  project_id uuid not null references app.projects(id) on delete cascade,
  organization_id uuid,
  schema_version integer not null,
  operation text not null,
  event_type text not null,
  occurred_at timestamptz not null,
  aggregate_type text not null,
  aggregate_id text not null,
  aggregate_version text,
  correlation_id text,
  causation_id text,
  actor_type text,
  actor_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint projection_outbox_schema_version_positive check (schema_version > 0),
  constraint projection_outbox_operation_check check (operation in ('UPSERT','DELETE','APPEND','REBUILD')),
  constraint projection_outbox_event_type_not_blank check (btrim(event_type) <> ''),
  constraint projection_outbox_aggregate_type_not_blank check (btrim(aggregate_type) <> ''),
  constraint projection_outbox_aggregate_id_not_blank check (btrim(aggregate_id) <> '')
);

create index if not exists projection_outbox_project_sequence_idx
  on orchestration.projection_outbox (project_id, sequence_id);
create index if not exists projection_outbox_project_type_sequence_idx
  on orchestration.projection_outbox (project_id, event_type, sequence_id);

alter table orchestration.projection_outbox enable row level security;
revoke all on table orchestration.projection_outbox from anon, authenticated;
grant all on table orchestration.projection_outbox to service_role;

grant usage, select on sequence orchestration.projection_outbox_sequence_id_seq to service_role;
revoke all on sequence orchestration.projection_outbox_sequence_id_seq from anon, authenticated;

comment on table orchestration.projection_outbox is 'Append-only ordered projection event log. Independent projection consumers advance their own orchestration.projection_checkpoints without competing for event claims.';
