import Link from 'next/link'
import { AlertTriangle, ArrowRight, CheckCircle2, CircleDollarSign, Database, FileWarning, Gauge, Layers3, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { requireUser } from '@/lib/supabase/auth'
import { createClient } from '@/lib/supabase/server'

type Dataset = { id: string; name: string; status: string; business_domain: string | null }
type Version = { id: string; dataset_id: string; status: string; version_number: number }
type Run = { id: string; dataset_version_id: string; status: string; started_at: string | null; row_count: number | null }
type Score = { profile_run_id: string; overall_score: number | null; completeness_score: number | null; validity_score: number | null; uniqueness_score: number | null; accuracy_score: number | null }
type Finding = { id: string; profile_run_id: string; severity: string; finding_type: string; title: string; description: string; recommendation: Record<string, unknown> | null }
type Source = { id: string; status: string }
type QualityRun = { id: string; status: string; passed: boolean | null }
type ObservabilityAlert = { id: string; category: string; severity: string; status: string; title: string }
type AgentRun = { id: string; status: string; error_code: string | null }

function percent(value: number | null | undefined) { return typeof value === 'number' ? `${Math.round(value * 100)}%` : 'N/A' }
function scoreTone(value: number | null) { if (value === null) return 'text-slate-400'; if (value >= .9) return 'text-emerald-600'; if (value >= .75) return 'text-blue-600'; if (value >= .6) return 'text-amber-600'; return 'text-red-600' }

export default async function DashboardPage() {
  const user = await requireUser()
  const supabase = await createClient()
  const [datasetsResult, versionsResult, runsResult, scoresResult, findingsResult, sourcesResult, qualityRunsResult, alertsResult, agentRunsResult] = await Promise.all([
    supabase.schema('catalog').from('datasets').select('id,name,status,business_domain').order('created_at', { ascending: false }),
    supabase.schema('catalog').from('dataset_versions').select('id,dataset_id,status,version_number').order('version_number', { ascending: false }),
    supabase.schema('profiling').from('profile_runs').select('id,dataset_version_id,status,started_at,row_count').order('started_at', { ascending: false }).limit(100),
    supabase.schema('profiling').from('data_quality_scores').select('profile_run_id,overall_score,completeness_score,validity_score,uniqueness_score,accuracy_score').order('created_at', { ascending: false }).limit(100),
    supabase.schema('profiling').from('profile_findings').select('id,profile_run_id,severity,finding_type,title,description,recommendation').order('created_at', { ascending: false }).limit(100),
    supabase.schema('catalog').from('data_sources').select('id,status'),
    supabase.schema('profiling').from('quality_rule_runs').select('id,status,passed').order('started_at', { ascending: false }).limit(500),
    supabase.schema('profiling').from('observability_alerts').select('id,category,severity,status,title').order('last_observed_at', { ascending: false }).limit(100),
    supabase.schema('agent').from('agent_runs').select('id,status,error_code').order('created_at', { ascending: false }).limit(100),
  ])
  if (datasetsResult.error) throw new Error(`Unable to load datasets: ${datasetsResult.error.message}`)
  if (versionsResult.error) throw new Error(`Unable to load dataset versions: ${versionsResult.error.message}`)
  if (runsResult.error) throw new Error(`Unable to load profiling runs: ${runsResult.error.message}`)
  if (scoresResult.error) throw new Error(`Unable to load quality scores: ${scoresResult.error.message}`)
  if (findingsResult.error) throw new Error(`Unable to load findings: ${findingsResult.error.message}`)
  if (sourcesResult.error) throw new Error(`Unable to load connections: ${sourcesResult.error.message}`)
  if (qualityRunsResult.error) throw new Error(`Unable to load quality control outcomes: ${qualityRunsResult.error.message}`)
  if (alertsResult.error) throw new Error(`Unable to load observability alerts: ${alertsResult.error.message}`)
  if (agentRunsResult.error) throw new Error(`Unable to load job health: ${agentRunsResult.error.message}`)

  const datasets = (datasetsResult.data ?? []) as Dataset[]
  const versions = (versionsResult.data ?? []) as Version[]
  const runs = (runsResult.data ?? []) as Run[]
  const scores = (scoresResult.data ?? []) as Score[]
  const findings = (findingsResult.data ?? []) as Finding[]
  const sources = (sourcesResult.data ?? []) as Source[]
  const qualityRuns = (qualityRunsResult.data ?? []) as QualityRun[]
  const observabilityAlerts = (alertsResult.data ?? []) as ObservabilityAlert[]
  const agentRuns = (agentRunsResult.data ?? []) as AgentRun[]
  const versionsById = new Map(versions.map(v => [v.id, v]))
  const scoresByRun = new Map(scores.map(s => [s.profile_run_id, s]))
  const latestRunByDataset = new Map<string, Run>()
  for (const run of runs) { const version = versionsById.get(run.dataset_version_id); if (version && !latestRunByDataset.has(version.dataset_id)) latestRunByDataset.set(version.dataset_id, run) }
  const completedRuns = runs.filter(r => r.status === 'COMPLETED')
  const scoredRuns = completedRuns.filter(r => typeof scoresByRun.get(r.id)?.overall_score === 'number')
  const overallScore = scoredRuns.length ? scoredRuns.reduce((sum, r) => sum + (scoresByRun.get(r.id)?.overall_score ?? 0), 0) / scoredRuns.length : null
  const highFindings = findings.filter(f => ['HIGH','CRITICAL'].includes(String(f.severity).toUpperCase()))
  const materialFindings = findings.filter(f => ['HIGH','CRITICAL','MEDIUM'].includes(String(f.severity).toUpperCase()))
  const affectedDatasetIds = new Set(findings.map(f => { const run = runs.find(r => r.id === f.profile_run_id); return run ? versionsById.get(run.dataset_version_id)?.dataset_id : undefined }).filter(Boolean))
  const readySources = sources.filter(s => s.status === 'ACTIVE').length
  const readyDatasets = datasets.filter(d => latestRunByDataset.get(d.id)?.status === 'COMPLETED').length
  const governanceCoverage = datasets.length ? Math.round((readyDatasets / datasets.length) * 100) : 0
  const topFindings = [...materialFindings].sort((a,b) => { const rank=(s:string)=>s==='CRITICAL'?4:s==='HIGH'?3:s==='MEDIUM'?2:1; return rank(String(b.severity).toUpperCase())-rank(String(a.severity).toUpperCase()) }).slice(0,5)
  const domainCounts = datasets.reduce<Record<string,number>>((a,d)=>{ const k=d.business_domain||'Unassigned'; a[k]=(a[k]??0)+1; return a },{})
  const sensitivityFindings = findings.filter(f => String(f.finding_type).toUpperCase().includes('SENSIT'))
  const failedQualityControls = qualityRuns.filter(run => run.status === 'FAILED').length
  const openGovernanceAlerts = observabilityAlerts.filter(alert => alert.status !== 'RESOLVED')
  const schemaDriftAlerts = openGovernanceAlerts.filter(alert => alert.category === 'SCHEMA_DRIFT').length
  const failedJobs = agentRuns.filter(run => run.status === 'FAILED').length
  const coverageGap = Math.max(0, datasets.length - readyDatasets)

  return <main className="min-h-screen bg-[radial-gradient(circle_at_5%_0%,_rgba(219,234,254,0.95),_transparent_28%),radial-gradient(circle_at_95%_5%,_rgba(243,232,255,0.9),_transparent_26%),linear-gradient(180deg,_#f8fbff_0%,_#ffffff_45%,_#f8fafc_100%)] text-slate-950"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8">
    <nav className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/80 bg-white/90 px-5 py-3 shadow-sm backdrop-blur"><Link href="/dashboard" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white shadow-sm"><Layers3 className="h-5 w-5"/></span><span><span className="block text-sm font-bold">Data Governance PowerHouse</span><span className="block text-xs text-slate-500">Executive governance view</span></span></Link><div className="flex flex-wrap gap-2 text-sm"><Link href="/datasets" className="rounded-xl px-3 py-2 font-medium text-slate-600 hover:bg-blue-50 hover:text-blue-700">Connections & Datasets</Link><Link href="/data-quality" className="rounded-xl px-3 py-2 font-medium text-slate-600 hover:bg-blue-50 hover:text-blue-700">Data Quality</Link><Link href="/observability" className="rounded-xl px-3 py-2 font-medium text-slate-600 hover:bg-blue-50 hover:text-blue-700">Observability</Link><Link href="/agents" className="rounded-xl bg-slate-950 px-4 py-2 font-semibold text-white hover:bg-blue-700">AI Agents</Link></div></nav>
    <section className="relative overflow-hidden rounded-3xl border border-blue-100 bg-white/95 p-7 shadow-[0_24px_80px_rgba(37,99,235,0.12)] sm:p-9"><div className="absolute -right-24 -top-28 h-72 w-72 rounded-full bg-blue-100/80 blur-3xl"/><div className="absolute -bottom-28 left-1/3 h-64 w-64 rounded-full bg-purple-100/70 blur-3xl"/><div className="relative grid gap-8 lg:grid-cols-[1fr_300px] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700"><Sparkles className="h-3.5 w-3.5"/> Executive governance summary</div><h1 className="mt-4 max-w-4xl text-3xl font-bold tracking-tight sm:text-5xl">Is poor data quality putting the business at risk?</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">A business first view of where data can affect revenue, customers, regulatory confidence and operational decisions. The numbers below reflect evidence persisted by the platform, not assumed business losses.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/data-quality" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-blue-700">Review business risks <ArrowRight className="h-4 w-4"/></Link><Link href="/datasets" className="inline-flex items-center rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-slate-700 hover:border-blue-200 hover:bg-blue-50">Improve governance coverage</Link></div></div><div className="rounded-3xl border border-emerald-100 bg-gradient-to-br from-emerald-50 to-white p-6 text-center shadow-sm"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-white shadow-md"><Gauge className={`h-10 w-10 ${scoreTone(overallScore)}`}/></div><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">Overall data health</p><p className={`mt-1 text-4xl font-black ${scoreTone(overallScore)}`}>{percent(overallScore)}</p><p className="mt-2 text-sm font-medium text-slate-600">{overallScore===null?'Build the evidence base':overallScore>=.8?'Generally trusted for decisions':'Attention required before relying on it broadly'}</p></div></div></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div className="rounded-2xl border border-blue-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><Database className="h-5 w-5"/></span><span className="text-xs font-semibold text-slate-400">ASSETS</span></div><p className="mt-4 text-3xl font-black">{datasets.length}</p><p className="text-sm font-medium text-slate-500">Governed datasets</p></div><div className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><CheckCircle2 className="h-5 w-5"/></span><span className="text-xs font-semibold text-slate-400">COVERAGE</span></div><p className="mt-4 text-3xl font-black">{governanceCoverage}%</p><p className="text-sm font-medium text-slate-500">Datasets with profiling evidence</p></div><div className="rounded-2xl border border-amber-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600"><AlertTriangle className="h-5 w-5"/></span><span className="text-xs font-semibold text-slate-400">EXPOSURE</span></div><p className="mt-4 text-3xl font-black">{affectedDatasetIds.size}</p><p className="text-sm font-medium text-slate-500">Datasets with findings</p></div><div className="rounded-2xl border border-red-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-red-600"><FileWarning className="h-5 w-5"/></span><span className="text-xs font-semibold text-slate-400">PRIORITY</span></div><p className="mt-4 text-3xl font-black">{highFindings.length}</p><p className="text-sm font-medium text-slate-500">High or critical issues</p></div><div className="rounded-2xl border border-purple-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-purple-50 text-purple-600"><ShieldCheck className="h-5 w-5"/></span><span className="text-xs font-semibold text-slate-400">TRUST</span></div><p className="mt-4 text-3xl font-black">{readySources}/{sources.length}</p><p className="text-sm font-medium text-slate-500">Connections ready for use</p></div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-blue-600"/><h2 className="text-xl font-bold">Governance observations</h2></div><p className="mt-1 text-sm text-slate-500">Evidence-led observations from profiling, automated controls, observability and job execution. Counts are persisted platform evidence.</p></div><Link href="/observability" className="text-sm font-bold text-blue-600">Inspect signals</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2">
      <div className="rounded-2xl border border-purple-100 bg-purple-50/70 p-5"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-purple-600"/><div className="font-bold">Sensitive data exposure</div></div><p className="mt-3 text-3xl font-black">{sensitivityFindings.length}</p><p className="mt-1 text-sm leading-6 text-slate-600">{sensitivityFindings.length ? 'Sensitive-data indicators are present in persisted profiling findings and should be covered by classification and access controls.' : 'No sensitivity findings are currently persisted.'}</p></div>
      <div className="rounded-2xl border border-red-100 bg-red-50/70 p-5"><div className="flex items-center gap-3"><FileWarning className="h-5 w-5 text-red-600"/><div className="font-bold">Quality control failures</div></div><p className="mt-3 text-3xl font-black">{failedQualityControls}</p><p className="mt-1 text-sm leading-6 text-slate-600">{failedQualityControls ? 'Automated data quality controls have failed and require evidence-based remediation.' : 'No automated quality control failures are currently persisted.'}</p></div>
      <div className="rounded-2xl border border-amber-100 bg-amber-50/70 p-5"><div className="flex items-center gap-3"><AlertTriangle className="h-5 w-5 text-amber-600"/><div className="font-bold">Change and drift signals</div></div><p className="mt-3 text-3xl font-black">{openGovernanceAlerts.length}</p><p className="mt-1 text-sm leading-6 text-slate-600">{schemaDriftAlerts ? `${schemaDriftAlerts} open schema drift alert${schemaDriftAlerts === 1 ? '' : 's'} require compatibility review.` : openGovernanceAlerts.length ? 'Open governance alerts are based on score, volume or quality-control changes.' : 'No open observability alerts are currently persisted.'}</p></div>
      <div className="rounded-2xl border border-blue-100 bg-blue-50/70 p-5"><div className="flex items-center gap-3"><Database className="h-5 w-5 text-blue-600"/><div className="font-bold">Coverage and execution</div></div><p className="mt-3 text-3xl font-black">{coverageGap}</p><p className="mt-1 text-sm leading-6 text-slate-600">{coverageGap ? `${coverageGap} governed dataset${coverageGap === 1 ? '' : 's'} currently lack completed profiling evidence.` : 'All registered datasets currently have completed profiling evidence.'} {failedJobs ? `${failedJobs} recent agent job${failedJobs === 1 ? '' : 's'} failed and remain visible in Job Monitor.` : ''}</p></div>
    </div></div><div className="rounded-3xl border border-purple-100 bg-gradient-to-br from-purple-50 to-white p-6 shadow-sm sm:p-7"><h2 className="text-xl font-bold">Priority actions</h2><p className="mt-1 text-sm text-slate-500">Start with evidence that can affect confidence and continuity.</p><div className="mt-6 space-y-3"><Link href="/data-quality" className="flex items-center justify-between rounded-xl border border-white bg-white p-4 shadow-sm hover:border-blue-200"><span><strong>Review critical findings</strong><span className="block text-xs text-slate-500">{highFindings.length} high or critical issues</span></span><ArrowRight className="h-4 w-4 text-blue-600"/></Link><Link href="/datasets" className="flex items-center justify-between rounded-xl border border-white bg-white p-4 shadow-sm hover:border-blue-200"><span><strong>Improve coverage</strong><span className="block text-xs text-slate-500">{datasets.length} governed datasets</span></span><ArrowRight className="h-4 w-4 text-blue-600"/></Link><Link href="/datasets" className="flex items-center justify-between rounded-xl border border-white bg-white p-4 shadow-sm hover:border-blue-200"><span><strong>Resolve connection readiness</strong><span className="block text-xs text-slate-500">{readySources}/{sources.length} ready</span></span><ArrowRight className="h-4 w-4 text-blue-600"/></Link></div></div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><h2 className="text-xl font-bold">Where attention is concentrated</h2><p className="mt-1 text-sm text-slate-500">Business domains are shown only when present in registered dataset metadata.</p><div className="mt-5 space-y-3">{Object.entries(domainCounts).length ? Object.entries(domainCounts).map(([domain,count])=><div key={domain} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><span className="font-medium text-slate-700">{domain}</span><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{count} dataset{count===1?'':'s'}</span></div>) : <p className="text-sm text-slate-500">No business domains have been assigned yet.</p>}</div></div><div className="rounded-3xl border border-red-100 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Priority findings</h2><p className="mt-1 text-sm text-slate-500">Highest severity evidence currently persisted.</p></div><Link href="/data-quality" className="text-sm font-bold text-blue-600">View all</Link></div><div className="mt-5 space-y-3">{topFindings.length ? topFindings.map(f=><div key={f.id} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><div className="flex items-start justify-between gap-3"><div className="font-semibold text-slate-800">{f.title}</div><span className="rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-[11px] font-bold text-red-700">{f.severity}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{f.description}</p><p className="mt-2 text-xs font-medium text-slate-500">Business consequence: {String(f.finding_type).toLowerCase().includes('null')?'incomplete information can weaken decisions and downstream processing.':String(f.finding_type).toLowerCase().includes('duplicate')?'duplicate information can distort volumes and customer views.':'the issue can reduce confidence and increase manual remediation.'}</p></div>) : <div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-800">No high or critical findings are currently persisted.</div>}</div></div></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><Link href="/profiling" className="rounded-2xl border border-blue-100 bg-white p-5 shadow-sm hover:border-blue-300 hover:shadow-md"><div className="font-bold">Profiling evidence</div><p className="mt-2 text-sm text-slate-500">Inspect the metrics, findings and quality scores behind this summary.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-blue-600">Open workspace <ArrowRight className="h-4 w-4"/></span></Link><Link href="/observability" className="rounded-2xl border border-purple-100 bg-white p-5 shadow-sm hover:border-purple-300 hover:shadow-md"><div className="font-bold">Monitor change</div><p className="mt-2 text-sm text-slate-500">Track changes in quality, freshness and operational signals over time.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-purple-600">Open observability <ArrowRight className="h-4 w-4"/></span></Link><Link href="/agents" className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm hover:border-emerald-300 hover:shadow-md"><div className="font-bold">Automate next actions</div><p className="mt-2 text-sm text-slate-500">Use governed AI agent capabilities to investigate evidence and recommend action.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-600">Open AI agents <ArrowRight className="h-4 w-4"/></span></Link></section>
    <footer className="mt-7 flex flex-wrap justify-between gap-3 rounded-2xl border border-slate-200 bg-white/80 px-5 py-4 text-xs text-slate-500"><span>Signed in as {user.email ?? 'current user'}</span><span>Governance decisions are based on persisted platform evidence.</span></footer>
  </div></main>
}
