import Link from 'next/link'
import { Gauge, OctagonX, ShieldCheck } from 'lucide-react'

import { authorizeProject } from '@/lib/auth/authorize'
import { createGovernanceResourceControlState } from '@/lib/ai/governance-resource-control-state'
import { requireUser } from '@/lib/supabase/auth'
import { createClient } from '@/lib/supabase/server'

type Project = { id: string; name: string }

type LeaseStateInput = { released_at: string | null; expires_at: string }

function valueOrDash(value: number | string | null) {
  return value == null ? 'Not set' : String(value)
}

function leaseState(lease: LeaseStateInput) {
  if (lease.released_at) return 'RELEASED'
  const expiresAt = Date.parse(lease.expires_at)
  return Number.isFinite(expiresAt) && expiresAt > Date.now() ? 'ACTIVE' : 'EXPIRED'
}

export default async function ResourceControlsPage({ searchParams }: { searchParams: Promise<{ projectId?: string }> }) {
  const user = await requireUser()
  const params = await searchParams
  const supabase = await createClient()
  const projectsResult = await supabase.schema('app').from('projects').select('id,name').order('name')
  if (projectsResult.error) throw new Error(`Unable to load projects: ${projectsResult.error.message}`)
  const projects = (projectsResult.data ?? []) as Project[]
  const selectedProjectId = projects.some((project) => project.id === params.projectId) ? params.projectId! : projects[0]?.id
  const state = selectedProjectId ? await (async () => {
    await authorizeProject(user.id, selectedProjectId, 'admin.manage')
    return createGovernanceResourceControlState().read(selectedProjectId)
  })() : null

  return <main className="min-h-screen bg-slate-50 p-5 sm:p-8">
    <div className="mx-auto max-w-7xl space-y-7">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <Link href={selectedProjectId ? `/admin/ai-command-center?projectId=${selectedProjectId}` : '/admin/ai-command-center'} className="text-sm font-semibold text-slate-600">← AI Command Center</Link>
        <Link href="/admin" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Administration</Link>
      </div>

      <header className="rounded-3xl border bg-white p-7 shadow-sm">
        <div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-600 text-white"><Gauge className="h-6 w-6"/></span><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-600">Governed execution controls</p><h1 className="text-3xl font-black">Resource Budgets, Pricing & Emergency State</h1><p className="mt-2 max-w-4xl text-sm text-slate-600">Read-only visibility from canonical governance policy, approved pricing evidence, atomic admission accounting, and execution-controller evidence. Observed telemetry cost or token usage never creates budget or pricing authority, and this page exposes no mutation action.</p></div></div>
      </header>

      <form method="get" className="rounded-2xl border bg-white p-5"><label className="block text-sm font-semibold">Project<select name="projectId" defaultValue={selectedProjectId} className="mt-2 block w-full max-w-xl rounded-xl border bg-white px-3 py-2 font-normal">{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><button className="mt-3 rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-bold text-white">Load control evidence</button></form>

      {!state ? <section className="rounded-2xl border bg-white p-6 text-sm text-slate-600">No authorized project is available for this account.</section> : <>
        <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
          <article className="rounded-2xl border bg-white p-5"><Gauge className="h-5 w-5"/><p className="mt-3 text-3xl font-black">{state.counts.effectiveBudgets}</p><p className="text-xs font-bold uppercase text-slate-500">Budget scopes</p></article>
          <article className="rounded-2xl border bg-white p-5"><ShieldCheck className="h-5 w-5"/><p className="mt-3 text-3xl font-black">{state.counts.enabledBudgets}</p><p className="text-xs font-bold uppercase text-slate-500">Enabled budgets</p></article>
          <article className="rounded-2xl border bg-white p-5"><ShieldCheck className="h-5 w-5"/><p className="mt-3 text-3xl font-black">{state.counts.effectiveModelPricing}</p><p className="text-xs font-bold uppercase text-slate-500">Pricing authorities</p></article>
          <article className="rounded-2xl border bg-white p-5"><Gauge className="h-5 w-5"/><p className="mt-3 text-3xl font-black">{state.counts.recentBudgetAdmissions}</p><p className="text-xs font-bold uppercase text-slate-500">Recent admissions</p></article>
          <article className="rounded-2xl border bg-white p-5"><ShieldCheck className="h-5 w-5"/><p className="mt-3 text-3xl font-black">{state.counts.activeBudgetConcurrencyLeases}</p><p className="text-xs font-bold uppercase text-slate-500">Active leases</p></article>
          <article className="rounded-2xl border bg-white p-5"><OctagonX className="h-5 w-5"/><p className="mt-3 text-3xl font-black">{state.counts.killedScopes}</p><p className="text-xs font-bold uppercase text-slate-500">Killed scopes</p></article>
          <article className="rounded-2xl border bg-white p-5"><OctagonX className="h-5 w-5"/><p className="mt-3 text-3xl font-black">{state.counts.pausedScopes}</p><p className="text-xs font-bold uppercase text-slate-500">Paused scopes</p></article>
          <article className="rounded-2xl border bg-white p-5"><ShieldCheck className="h-5 w-5"/><p className="mt-3 text-3xl font-black">{state.counts.runningScopes}</p><p className="text-xs font-bold uppercase text-slate-500">Resumed scopes</p></article>
        </section>

        <section className="rounded-2xl border bg-white p-6">
          <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">Project output-token enforcement readiness</h2><p className="mt-1 max-w-4xl text-sm text-slate-500">Derived only from the canonical effective PROJECT / PROJECT resource-budget row. This status does not create a policy or infer authority from runtime telemetry.</p></div><span className="rounded-full border px-3 py-1 text-xs font-black">{state.projectOutputBudget.status}</span></div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2"><p className="rounded-xl bg-slate-50 p-4 text-sm"><span className="font-semibold">Governed output ceiling:</span> {valueOrDash(state.projectOutputBudget.maxOutputTokens)}{state.projectOutputBudget.maxOutputTokens != null ? ' tokens/request' : ''}</p><p className="rounded-xl bg-slate-50 p-4 text-sm"><span className="font-semibold">Canonical policy ID:</span> <span className="font-mono text-xs">{state.projectOutputBudget.policyId ?? 'Not recorded'}</span></p></div>
          {state.projectOutputBudget.status === 'NOT_CONFIGURED' ? <p className="mt-4 rounded-xl border border-dashed p-4 text-sm text-slate-600">Runtime output-ceiling enforcement is available, but no canonical PROJECT / PROJECT budget policy is recorded. No ceiling is invented.</p> : null}
          {state.projectOutputBudget.status === 'DISABLED' ? <p className="mt-4 rounded-xl border border-dashed p-4 text-sm text-slate-600">A canonical PROJECT / PROJECT policy exists but is disabled, so it supplies no active output-token ceiling.</p> : null}
          {state.projectOutputBudget.status === 'NO_OUTPUT_LIMIT' ? <p className="mt-4 rounded-xl border border-dashed p-4 text-sm text-slate-600">An enabled canonical PROJECT / PROJECT policy exists without max_output_tokens_per_request, so no project output ceiling is enforced.</p> : null}
          {state.projectOutputBudget.status === 'READY' ? <p className="mt-4 rounded-xl border p-4 text-sm text-slate-600">The canonical project output-token ceiling is configured for pre-invocation enforcement. Caller requests below it remain lower; requests above it are capped.</p> : null}
        </section>

        <section className="rounded-2xl border bg-white p-6"><div><h2 className="text-xl font-black">Effective resource budget policies</h2><p className="mt-1 max-w-4xl text-sm text-slate-500">Each row is the latest recorded policy version for its project/scope. Limits are explicit policy evidence and are not calculated from telemetry consumption.</p></div><div className="mt-5 overflow-x-auto">{state.budgets.length ? <table className="w-full min-w-[1200px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Scope</th><th className="p-3">Enabled</th><th className="p-3">Input tokens/request</th><th className="p-3">Output tokens/request</th><th className="p-3">Cost/request USD</th><th className="p-3">Cost/day USD</th><th className="p-3">Requests/min</th><th className="p-3">Concurrent</th><th className="p-3">Reviewer</th></tr></thead><tbody>{state.budgets.map((budget) => <tr key={budget.id} className="border-b last:border-0"><td className="p-3 font-bold">{budget.scope_type}<p className="font-mono text-[11px] text-slate-400">{budget.scope_key}</p></td><td className="p-3">{budget.enabled ? 'YES' : 'NO'}</td><td className="p-3">{valueOrDash(budget.max_input_tokens_per_request)}</td><td className="p-3">{valueOrDash(budget.max_output_tokens_per_request)}</td><td className="p-3">{valueOrDash(budget.max_cost_usd_per_request)}</td><td className="p-3">{valueOrDash(budget.max_cost_usd_per_day)}</td><td className="p-3">{valueOrDash(budget.max_requests_per_minute)}</td><td className="p-3">{valueOrDash(budget.max_concurrent_executions)}</td><td className="p-3">{budget.reviewer_capability}<p className="text-xs text-slate-400">{budget.review_note}</p></td></tr>)}</tbody></table> : <p className="rounded-xl border border-dashed p-4 text-sm text-slate-500">No canonical resource budget policy has been recorded for this project. This means no budget authority is represented here; telemetry usage must not be treated as a substitute.</p>}</div></section>

        <section className="rounded-2xl border bg-white p-6">
          <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">Effective model pricing authority</h2><p className="mt-1 max-w-4xl text-sm text-slate-500">Current human-reviewed provider/model pricing evidence from the canonical governance view. Prices are shown in their recorded currency and exact 1,000,000-token unit. No FX conversion, telemetry-derived price, spend calculation, or runtime cost enforcement is performed here.</p></div><span className="rounded-full border px-3 py-1 text-xs font-black">READ ONLY</span></div>
          <div className="mt-5 overflow-x-auto">{state.modelPricing.length ? <table className="w-full min-w-[1500px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Provider / model</th><th className="p-3">Version</th><th className="p-3">Currency</th><th className="p-3">Input / 1M tokens</th><th className="p-3">Output / 1M tokens</th><th className="p-3">Effective window</th><th className="p-3">Source</th><th className="p-3">Review authority</th></tr></thead><tbody>{state.modelPricing.map((pricing) => <tr key={pricing.id} className="border-b align-top last:border-0"><td className="p-3 font-bold">{pricing.provider}<p className="mt-1 font-mono text-xs font-normal text-slate-500">{pricing.model_id}</p></td><td className="p-3 font-mono text-xs">{pricing.pricing_version}</td><td className="p-3 font-bold">{pricing.currency}</td><td className="p-3 font-mono">{String(pricing.input_price_per_million_tokens)}</td><td className="p-3 font-mono">{String(pricing.output_price_per_million_tokens)}</td><td className="p-3 text-xs"><p>{new Date(pricing.effective_from).toLocaleString()}</p><p className="mt-1 text-slate-500">to {pricing.effective_to ? new Date(pricing.effective_to).toLocaleString() : 'open-ended'}</p></td><td className="max-w-sm p-3"><p>{pricing.source_reference}</p>{pricing.source_uri ? <p className="mt-1 break-all font-mono text-[11px] text-slate-500">{pricing.source_uri}</p> : null}</td><td className="max-w-sm p-3"><p className="font-semibold">{pricing.reviewer_capability}</p><p className="mt-1 text-xs text-slate-500">Reviewed {new Date(pricing.reviewed_at).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">{pricing.review_note}</p></td></tr>)}</tbody></table> : <div className="rounded-xl border border-dashed p-5"><p className="font-semibold text-slate-700">No approved pricing configured.</p><p className="mt-1 text-sm text-slate-500">No effective human-reviewed model pricing authority exists for this project. DataNexus will not invent provider prices, derive them from telemetry, calculate governed spend, perform FX conversion, or enable runtime USD cost enforcement.</p></div>}</div>
        </section>

        <section className="rounded-2xl border bg-white p-6"><div><h2 className="text-xl font-black">Recent atomic request admissions</h2><p className="mt-1 max-w-4xl text-sm text-slate-500">Latest 100 canonical PROJECT-scope admissions. These records prove execution accounting against an exact policy version; they do not approve a model, policy, or AI system.</p></div><div className="mt-5 overflow-x-auto">{state.budgetAdmissions.length ? <table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Admitted</th><th className="p-3">Policy version</th><th className="p-3">Admission</th><th className="p-3">Execution correlation</th></tr></thead><tbody>{state.budgetAdmissions.map((admission) => <tr key={admission.id} className="border-b last:border-0"><td className="p-3 text-xs">{new Date(admission.admitted_at).toLocaleString()}</td><td className="p-3 font-mono text-xs">{admission.policy_version_id}</td><td className="p-3 font-mono text-xs">{admission.id}</td><td className="p-3 font-mono text-xs">{admission.correlation_id}</td></tr>)}</tbody></table> : <p className="rounded-xl border border-dashed p-4 text-sm text-slate-500">No canonical request admissions are recorded for this project. This does not imply a configured rate or concurrency limit.</p>}</div></section>

        <section className="rounded-2xl border bg-white p-6"><div><h2 className="text-xl font-black">Recent concurrency leases</h2><p className="mt-1 max-w-4xl text-sm text-slate-500">Latest 100 canonical concurrency leases. ACTIVE means unreleased and not yet expired at render time; release and expiry are capacity accounting only, never governance authority.</p></div><div className="mt-5 overflow-x-auto">{state.budgetConcurrencyLeases.length ? <table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">State</th><th className="p-3">Acquired</th><th className="p-3">Expires</th><th className="p-3">Released</th><th className="p-3">Policy version</th><th className="p-3">Lease</th><th className="p-3">Execution correlation</th></tr></thead><tbody>{state.budgetConcurrencyLeases.map((lease) => <tr key={lease.id} className="border-b last:border-0"><td className="p-3 font-black">{leaseState(lease)}</td><td className="p-3 text-xs">{new Date(lease.acquired_at).toLocaleString()}</td><td className="p-3 text-xs">{new Date(lease.expires_at).toLocaleString()}</td><td className="p-3 text-xs">{lease.released_at ? new Date(lease.released_at).toLocaleString() : 'Not released'}</td><td className="p-3 font-mono text-xs">{lease.policy_version_id}</td><td className="p-3 font-mono text-xs">{lease.id}</td><td className="p-3 font-mono text-xs">{lease.correlation_id}</td></tr>)}</tbody></table> : <p className="rounded-xl border border-dashed p-4 text-sm text-slate-500">No canonical concurrency leases are recorded for this project.</p>}</div></section>

        <section className="rounded-2xl border bg-white p-6"><div><h2 className="text-xl font-black">Effective emergency execution state</h2><p className="mt-1 max-w-4xl text-sm text-slate-500">The latest append-only execution-controller event determines each scope shown. Absence of a row means no canonical execution-control state has been recorded.</p></div><div className="mt-5 space-y-3">{state.executionControls.length ? state.executionControls.map((control) => <article key={control.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{control.scope_type} · {control.scope_key}</p><p className="mt-1 text-sm text-slate-600">{control.reason}</p><p className="mt-2 text-xs text-slate-400">{control.actor_capability} · {new Date(control.created_at).toLocaleString()}</p></div><span className="rounded-full border px-3 py-1 text-xs font-black">{control.effective_state}</span></div></article>) : <p className="rounded-xl border border-dashed p-4 text-sm text-slate-500">No canonical pause, kill, or resume event is recorded for this project. This does not imply an inferred RUNNING state.</p>}</div></section>

        <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-black">Recent execution-control evidence</h2><p className="mt-1 text-sm text-slate-500">Latest 100 append-only controller events. These records preserve operator provenance and do not grant AI model approval.</p><div className="mt-5 overflow-x-auto">{state.executionControlEvents.length ? <table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="p-3">Created</th><th className="p-3">Scope</th><th className="p-3">Action</th><th className="p-3">Reason</th><th className="p-3">Actor capability</th><th className="p-3">Correlation</th></tr></thead><tbody>{state.executionControlEvents.map((event) => <tr key={event.id} className="border-b last:border-0"><td className="p-3 text-xs">{new Date(event.created_at).toLocaleString()}</td><td className="p-3">{event.scope_type}<p className="font-mono text-[11px] text-slate-400">{event.scope_key}</p></td><td className="p-3 font-black">{event.control_action}</td><td className="p-3">{event.reason}</td><td className="p-3">{event.actor_capability}</td><td className="p-3 font-mono text-xs">{event.correlation_id ?? 'Not recorded'}</td></tr>)}</tbody></table> : <p className="rounded-xl border border-dashed p-4 text-sm text-slate-500">No execution-control events are recorded for this project.</p>}</div></section>

        <section className="rounded-2xl border bg-slate-950 p-6 text-white"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5"/><h2 className="text-lg font-black">Authority boundary</h2></div><p className="mt-3 max-w-4xl text-sm text-slate-300">Budget policy constrains resource use. Approved pricing rows are pricing evidence only and do not calculate governed spend or enable runtime cost enforcement. Admission and lease records account for execution capacity. Execution-control state constrains execution. None of them approves an AI system, activates a model version, promotes learning, changes routing authority, or replaces exact-current-version human deployment approval. Mutation remains disabled in the Command Center.</p></section>
      </>}
    </div>
  </main>
}
